import React,{useEffect,useMemo,useRef,useState} from 'react';
import {House,ChartBar,FolderSimple,Files,Database,Robot,ClockCounterClockwise,BookOpen,Receipt,GearSix,Buildings,CaretDown,MagnifyingGlass,Question,Sun,Moon,List,CheckCircle,X,ArrowRight,Command,Bell,WarningCircle,CurrencyCircleDollar,ShieldCheck,PlugsConnected,Siren,CalendarCheck} from '@phosphor-icons/react';
import {AppContext} from './context';
import {titles,initialActivities,initialEvents,baseLedger,caseModels,exceptionMeta,packages as demoPackages} from './model';
import {Button,IconButton,Modal,Search,Empty} from './ui';
import {Activities,Overview,Assets,Cases,Payments,AgentScreen,Logs,Strategy,Integrations,Usage,Settings} from './screens';
import {CreateWizard,CaseDrawer,PolicyModal,ReceiptModal,ImportModal,PaymentDetailModal,ExceptionModal,ReconciliationModal} from './dialogs';
import {Exceptions} from './exceptions';
import {RepaymentPlanCreateModal,RepaymentPlanReviewModal,RepaymentPlans} from './repayment';
import {AICopilot} from './ai';
import {INTEGRATION_STORAGE_KEY,integrationGate,maskedCredential,restoreIntegrationState,sanitizeServiceConfig,serializeIntegrationState,serviceVersionSnapshot} from './integration-state';
import {determineActivityMode} from './activity-preflight';
import {buildOfflineRepaymentOverview,summarizeRepaymentPlans} from './repayment-state';
import {activityApi,agentApi,authApi,catalogApi,classifyApiFailure,integrationApi,jobApi,normalizeFinancialOverview,normalizeIntegrationOverview,paymentApi,protectionApi,repaymentApi,securityApi} from './api';
import {APP_VERSION,BRAND_ASSET,PRODUCT_DESCRIPTOR,PRODUCT_ENGLISH_NAME,PRODUCT_NAME} from './brand';
import {beginOidcLogin,completeOidcCallback,logoutOidc,oidcConfigured} from './oidc-client';
const nav=[['overview',House],['activities',ChartBar],['assets',FolderSimple],['cases',Files],['plans',CalendarCheck],['payments',Database],['agents',Robot],['exceptions',Siren],['logs',ClockCounterClockwise],['strategy',BookOpen],['integrations',PlugsConnected]];
const makeInitialServiceConfigs=()=>({
 TENANT_A:{
  agent:{provider:'Hermes Agent',endpoint:'http://agent-gateway.internal/v1',profile:'fulfill-agent-v3',authToken:maskedCredential,credentialConfigured:true,approval:'高影响动作需确认',transport:'sandbox-contract',safetyPreset:'fulfillops-safe',sessionPersistence:'database-checkpoint',saved:true,tested:true,latency:'126 ms',version:3,updatedAt:'2026.09.13 10:18'},
  model:{provider:'DeepSeek',endpoint:'https://api.deepseek.com',model:'deepseek-flash',apiKey:maskedCredential,credentialConfigured:true,timeout:'30',executionMode:'contract-only',maxOutputTokens:'512',maxCostUsd:'0.05',saved:true,tested:true,latency:'72 ms',version:2,updatedAt:'2026.09.13 10:22'},
  voice:{provider:'阿里云智能语音',region:'华东 2（上海）',asr:'Paraformer 实时版',tts:'CosyVoice · 龙橙',sampleRate:'16 kHz',accessKey:maskedCredential,credentialConfigured:true,saved:true,tested:false,latency:'—',version:1,updatedAt:'2026.09.13 10:26'},
  phone:{provider:'LiveKit SIP',sipHost:'sip.example.test:5061',trunk:'amc-demo-trunk',callerId:'010****8800',callback:'https://example.test/telephony/events',secret:maskedCredential,credentialConfigured:true,saved:true,tested:false,latency:'—',version:1,updatedAt:'2026.09.13 10:30'}
 },
 TENANT_B:{
  agent:{provider:'LangGraph Runtime',endpoint:'https://agent.example.test/v1',profile:'fulfill-agent',authToken:'',credentialConfigured:false,approval:'高影响动作需确认',transport:'sandbox-contract',safetyPreset:'fulfillops-safe',sessionPersistence:'database-checkpoint',saved:false,tested:false,latency:'—',version:1,updatedAt:'—'},
  model:{provider:'OpenAI Compatible',endpoint:'https://api.example.test/v1',model:'fulfill-model',apiKey:'',credentialConfigured:false,timeout:'30',executionMode:'contract-only',maxOutputTokens:'512',maxCostUsd:'0.05',saved:false,tested:false,latency:'—',version:1,updatedAt:'—'},
  voice:{provider:'火山引擎语音',region:'华北 2（北京）',asr:'流式语音识别',tts:'中文女声',sampleRate:'16 kHz',accessKey:'',credentialConfigured:false,saved:false,tested:false,latency:'—',version:1,updatedAt:'—'},
  phone:{provider:'标准 SIP Trunk',sipHost:'sip.example.test:5061',trunk:'tenant-b-demo',callerId:'021****6600',callback:'https://example.test/telephony/events',secret:'',credentialConfigured:false,saved:false,tested:false,latency:'—',version:1,updatedAt:'—'}
 }
});
const makeInitialIntegrationStates=()=>({
 TENANT_A:{enabled:false,lastRun:null,enabledAt:null,enabledBy:null,enabledServiceVersions:null,invalidatedReason:'语音与电话服务尚未完成连接测试'},
 TENANT_B:{enabled:false,lastRun:null,enabledAt:null,enabledBy:null,enabledServiceVersions:null,invalidatedReason:'尚未完成服务配置'}
});
const loadIntegrationBundle=()=>{
 const configs=makeInitialServiceConfigs();
 const states=makeInitialIntegrationStates();
 try{
  const persisted=JSON.parse(localStorage.getItem(INTEGRATION_STORAGE_KEY)||'null');
  return restoreIntegrationState(configs,states,persisted);
 }catch{return {configs,states}}
};
const formatNow=()=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()).replaceAll('/','.');
const addMonths=(value,count)=>{const date=new Date(`${value}T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+count);return date.toISOString().slice(0,10)};
const buildInstallments=(totalCents,downCents,count,firstDue)=>{if(count===1)return [{installment_no:1,due_date:firstDue,due_cents:totalCents}];const rest=totalCents-downCents;const regular=Math.floor(rest/(count-1));return Array.from({length:count},(_,index)=>({installment_no:index+1,due_date:addMonths(firstDue,index),due_cents:index===0?downCents:index===count-1?rest-regular*(count-2):regular}))};
const defaultQueueHealth={mode:'inline',status:'inline',active_workers:0,queued_jobs:0,running_jobs:0,stale_jobs:0,latest_heartbeat_at:null,lease_seconds:60,broker_backend:'database',broker_status:'polling'};
const defaultSecretHealth={backend:'reference-only',status:'reference-only',persistent:false,resolvable:false,key_version:null,active_secrets:0,rotation_pending:0,detail:'凭证由部署环境注入'};
const defaultAuthHealth={mode:'unconfigured',status:'degraded',issuer_configured:false,audience_configured:false,jwks_configured:false,allowed_algorithms:[],required_claims:['sub','exp','iat'],tenant_claim:null,leeway_seconds:0,jwks_cache_seconds:300,dev_header_enabled:false,dev_token_enabled:false,detail:'认证策略仅管理员可见'};
const defaultModelGateway={status:'unconfigured',configured:false,provider:null,model:null,config_version:null,execution_mode:'contract-only',endpoint_host:null,egress_allowed:false,credential_configured:false,live_calls_enabled:false,connected:false,max_output_tokens:0,max_cost_usd:0,detail:'模型网关仅管理员可见'};
const emptyFinancialOverview={summary:null,commissionLedger:[],pendingReceipts:[],reconciliations:[],webhookReady:false,webhookProvider:null,sandboxEnabled:false};
const emptyRepaymentOverview={active_count:0,pending_review_count:0,completed_count:0,overdue_plan_count:0,due_soon_count:0,plans:[]};
const offlineFinancialOverview=tenant=>tenant==='TENANT_A'?{
 summary:{confirmed_net_recovery_cents:1992000,commission_eligible_recovery_cents:1842000,accrued_commission_cents:277800,settled_commission_cents:0,collected_commission_cents:0,unsettled_commission_cents:277800,uncollected_settlement_cents:0,pending_receipt_count:1},
 commissionLedger:[],
 pendingReceipts:[{id:'PRC-DEMO-REVIEW',provider:'sandbox-amc',provider_event_id:'AMC-UNMATCHED-20260915',event_type:'payment',amount_cents:68800,currency:'CNY',occurred_at:'2026-09-15T09:20:00',case_id:null,original_provider_event_id:null,payload_digest:'7a9dfdd2c229df4ff0d009ab13fa980ce45a778a4c386e39c7a436ecaa72aef',signature_digest:'fa3120ad7d5bc0cc39946fdb34c8c179a8c38e6c69a25c68c59e4b678630a236',signature_version:'v1',signature_verified:true,status:'review_pending',failure_code:'human_review_pending',recovery_entry_id:null,duplicate_count:0,received_at:'2026-09-15T09:20:03',updated_at:'2026-09-15T09:28:00'}],
 reconciliations:[{id:'REC-DEMO-REVIEW',receipt_id:'PRC-DEMO-REVIEW',proposed_case_id:'C002',candidate_snapshot:[{case_id:'C002',package_id:'PKG_A',score:45,signals:['当前租户财务档案完整','存在已签履约方案','案件未处于保护暂停'],blocked:false,has_signed_plan:true}],evidence_digest:'564c648a8f587f7348343109e1409218f9d55a3d9e58dd7139c513d104a6ce7e',reason:'银行附言与已签方案付款信息一致，建议关联 C002',status:'pending_review',version:1,proposed_by:'test-operator',proposed_at:'2026-09-15T09:28:00',reviewed_by:null,reviewed_at:null,review_note:null,recovery_entry_id:null}],
 webhookReady:false,webhookProvider:null,sandboxEnabled:false,
}:emptyFinancialOverview;
const protectionCategoryCodes={'债务异议':'debt_dispute','停止联系':'stop_contact','身份冲突':'identity_conflict','委托到期':'mandate_expired','资料缺失':'data_quality','金额冲突':'amount_verification','授权缺失':'authorization_gap','号码缺失':'contact_data','预算耗尽':'budget_exhausted'};
const protectionActiveStatuses=['open','pending_review','permanent_hold'];
const summarizeProtection=incidents=>{const active=incidents.filter(row=>protectionActiveStatuses.includes(row.status));const now=Date.now();return {active_count:active.length,p0_count:active.filter(row=>row.priority==='P0').length,pending_review_count:active.filter(row=>row.status==='pending_review').length,overdue_count:active.filter(row=>row.sla_due_at&&new Date(row.sla_due_at).getTime()<now).length,permanent_hold_count:active.filter(row=>row.status==='permanent_hold').length,incidents}};
const offlineProtectionOverview=tenant=>{const tenantCases=caseModels(baseLedger,false).filter(row=>row.tenant_id===tenant);const incidents=tenantCases.filter(row=>row.blocked&&exceptionMeta[row.case_id]).map(row=>{const meta=exceptionMeta[row.case_id];const pending=row.case_id==='C010';const permanent=row.case_id==='C013';return {id:meta.id,case_id:row.case_id,source_event_id:`DEMO-GUARD-${row.case_id}`,category:protectionCategoryCodes[meta.category]||'data_quality',priority:meta.priority,reason:row.reason,opening_digest:`demo-opening-${row.case_id}`,owner:meta.owner,release_policy:permanent?'permanent_hold':['C014','C015'].includes(row.case_id)?'renewal_evidence':'maker_checker',status:permanent?'permanent_hold':pending?'pending_review':'open',version:pending?2:1,previous_case_status:'待联系',sla_due_at:null,opened_by:'system:guard',opened_at:'2026-09-15T09:45:00',resolution_note:pending?'异议事实和金额依据已复核，申请重新评估案件。':null,evidence_refs:pending?['EVIDENCE-DISPUTE-C010-01']:[],evidence_digest:pending?'demo-evidence-c010':null,proposed_by:pending?'test-operator':null,proposed_at:pending?'2026-09-15T11:20:00':null,reviewed_by:null,reviewed_at:null,review_note:null,resolved_at:null,case_released:false}});return summarizeProtection(incidents)};
export function App(){
 const hostedDemo=typeof window!=='undefined'&&window.location.protocol!=='file:'&&!['localhost','127.0.0.1','terminal.local'].includes(window.location.hostname);
 const [route,setRoute]=useState(location.hash.slice(2)||'overview');
 const [tenant,setTenant]=useState('TENANT_A');
 const [theme,setTheme]=useState('light');
 const [activities,setActivities]=useState(initialActivities);
 const [events,setEvents]=useState(initialEvents);
 const [ledger,setLedger]=useState(baseLedger);
 const [paid,setPaid]=useState(false);
 const [dialog,setDialog]=useState(null);
 const [caseId,setCaseId]=useState(null);
 const [caseTab,setCaseTab]=useState('概览');
 const [searchOpen,setSearchOpen]=useState(false);
 const [search,setSearch]=useState('');
 const [workspaceOpen,setWorkspaceOpen]=useState(false);
 const [toast,setToast]=useState('');
 const [mobileOpen,setMobileOpen]=useState(false);
 const [notificationOpen,setNotificationOpen]=useState(false);
 const [oidcReady,setOidcReady]=useState(false);
 const [notificationsRead,setNotificationsRead]=useState(false);
 const [scope,setScope]=useState('all');
 const [runSteps,setRunSteps]=useState({});
 const [policies,setPolicies]=useState({});
 const [organization,setOrganization]=useState({TENANT_A:'租户 A',TENANT_B:'租户 B'});
 const [notificationPreferences,setNotificationPreferences]=useState({exception:true,daily:false});
 const [integrationSeed]=useState(loadIntegrationBundle);
 const [serviceConfigsByTenant,setServiceConfigsByTenant]=useState(integrationSeed.configs);
 const [integrationStatesByTenant,setIntegrationStatesByTenant]=useState(integrationSeed.states);
 const [backendStatus,setBackendStatus]=useState('checking');
 const [backendError,setBackendError]=useState('');
 const [identity,setIdentity]=useState({actor_id:'Terry',display_name:'Terry',role:'admin',auth_mode:'local-demo'});
 const [agentGateway,setAgentGateway]=useState({mode:'local-demo',provider:'Hermes Agent',profile:'fulfill-agent-v3',connected:false,transport:'sandbox-contract',session_persistence:'database-checkpoint',tools:[],forbidden_tools:[]});
 const [queueHealth,setQueueHealth]=useState(defaultQueueHealth);
 const [secretHealth,setSecretHealth]=useState(defaultSecretHealth);
 const [authHealth,setAuthHealth]=useState(defaultAuthHealth);
 const [modelGateway,setModelGateway]=useState(defaultModelGateway);
 const [financialOverview,setFinancialOverview]=useState(()=>offlineFinancialOverview('TENANT_A'));
 const [protectionOverview,setProtectionOverview]=useState(()=>offlineProtectionOverview('TENANT_A'));
 const [repaymentOverview,setRepaymentOverview]=useState(()=>buildOfflineRepaymentOverview('TENANT_A',baseLedger));
 const [receivingPayment,setReceivingPayment]=useState(false);
 const [latestReplay,setLatestReplay]=useState(null);
 const [activeJob,setActiveJob]=useState(null);
 const agentSessions=useRef({});
 const [copilotOpen,setCopilotOpen]=useState(false);
 const [exceptionResolutions,setExceptionResolutions]=useState({});
 const [serverPackages,setServerPackages]=useState([]);
 const [serverCases,setServerCases]=useState([]);
 const [catalogTotals,setCatalogTotals]=useState({packages:0,cases:0});
 const [catalogRevision,setCatalogRevision]=useState(0);
 const [caseDetail,setCaseDetail]=useState(null);
 const offlineCases=useMemo(()=>caseModels(ledger,paid),[ledger,paid]);
 const cases=useMemo(()=>{
  const source=backendStatus==='connected'?serverCases:offlineCases;
  return source.map(c=>{const governedPlan=repaymentOverview.plans.find(plan=>plan.case_id===c.case_id&&['pending_review','active','completed'].includes(plan.status));const base=governedPlan?.status==='active'&&!c.blocked?{...c,status:'履约中',governedPlan}:{...c,governedPlan};return backendStatus!=='connected'&&exceptionResolutions[c.case_id]?.status==='resolved'?{...base,blocked:false,status:'待重新评估',reason:''}:base});
 },[backendStatus,serverCases,offlineCases,exceptionResolutions,repaymentOverview]);
 const packages=backendStatus==='connected'?serverPackages:demoPackages;
 const visibleCases=cases.filter(c=>c.tenant_id===tenant);
 const visiblePackages=packages.filter(p=>p.tenant_id===tenant);
 const visibleLedger=ledger.filter(t=>t.tenant_id===tenant);
 const visibleActivities=activities.filter(x=>x.tenant===tenant);
 const protectedCount=protectionOverview.active_count;
 const page=route.split('/')[0];
 const navigate=s=>{location.hash='/'+s;setRoute(s);setMobileOpen(false);setCaseId(null);setNotificationOpen(false)};
 const notify=s=>setToast(s);
 const applyFinancialPayload=payload=>{const normalized=normalizeFinancialOverview(payload,tenant);setLedger(all=>[...all.filter(row=>row.tenant_id!==tenant),...normalized.ledger]);setFinancialOverview(normalized);setPaid(normalized.ledger.some(row=>row.transaction_id==='sandbox-amc:SBX-ui-demo-payment-v1'));return normalized};
 const applyCatalogPayload=(packagePage,casePage)=>{setServerPackages(packagePage.items);setServerCases(casePage.items);setCatalogTotals({packages:packagePage.total,cases:casePage.total});setCatalogRevision(value=>value+1);return {packagePage,casePage}};
 const refreshCatalog=async()=>{const [packagePage,casePage]=await Promise.all([catalogApi.packages(tenant,{page:1,page_size:100}),catalogApi.cases(tenant,{page:1,page_size:100})]);return applyCatalogPayload(packagePage,casePage)};
 useEffect(()=>{const fn=()=>{setRoute(location.hash.slice(2)||'overview');setCaseId(null)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{setTheme(page==='agents'&&route.includes('/')?'dark':'light')},[route,page]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[route]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{try{localStorage.setItem(INTEGRATION_STORAGE_KEY,serializeIntegrationState(serviceConfigsByTenant,integrationStatesByTenant))}catch{}},[serviceConfigsByTenant,integrationStatesByTenant]);
 useEffect(()=>{let active=true;completeOidcCallback().catch(error=>{if(active){setBackendStatus('auth-required');setBackendError(error.message)}}).finally(()=>active&&setOidcReady(true));return()=>{active=false}},[]);
 useEffect(()=>{if(!oidcReady)return;let active=true;setBackendStatus('checking');setBackendError('');setQueueHealth(defaultQueueHealth);setSecretHealth(defaultSecretHealth);setAuthHealth(defaultAuthHealth);setModelGateway(defaultModelGateway);setFinancialOverview(emptyFinancialOverview);setProtectionOverview(summarizeProtection([]));setRepaymentOverview(emptyRepaymentOverview);setLatestReplay(null);setServerPackages([]);setServerCases([]);setCatalogTotals({packages:0,cases:0});setCaseDetail(null);Promise.all([integrationApi.get(tenant),authApi.session(tenant),agentApi.gateway(tenant),jobApi.queueHealth(tenant).catch(()=>defaultQueueHealth),securityApi.secretHealth(tenant).catch(()=>defaultSecretHealth),securityApi.authHealth(tenant).catch(()=>null),securityApi.modelGatewayHealth(tenant).catch(()=>defaultModelGateway),agentApi.replays(tenant).catch(()=>[]),paymentApi.overview(tenant).catch(()=>null),protectionApi.overview(tenant).catch(()=>null),repaymentApi.overview(tenant).catch(()=>null),catalogApi.packages(tenant,{page:1,page_size:100}),catalogApi.cases(tenant,{page:1,page_size:100})]).then(([payload,session,gateway,queue,secrets,auth,modelHealth,replays,financial,protections,repayments,packagePage,casePage])=>{if(!active)return;const normalized=normalizeIntegrationOverview(payload);setServiceConfigsByTenant(all=>({...all,[tenant]:{...all[tenant],...normalized.services}}));setIntegrationStatesByTenant(all=>({...all,[tenant]:normalized.state}));setIdentity(session);setAgentGateway(gateway);setQueueHealth(queue);setSecretHealth(secrets);setAuthHealth(auth||{...defaultAuthHealth,mode:session.auth_mode==='oidc'?'oidc':'unconfigured'});setModelGateway(modelHealth);setLatestReplay(replays[0]||null);applyCatalogPayload(packagePage,casePage);if(financial)applyFinancialPayload(financial);if(protections)setProtectionOverview(protections);if(repayments)setRepaymentOverview(repayments);setBackendStatus('connected')}).catch(error=>{if(active){const failure=classifyApiFailure(error);setBackendStatus(failure);setBackendError(error?.message||'业务 API 暂时不可用');setQueueHealth(defaultQueueHealth);setSecretHealth(defaultSecretHealth);setAuthHealth(defaultAuthHealth);setModelGateway(defaultModelGateway);setServerPackages([]);setServerCases([]);setCatalogTotals({packages:0,cases:0});setFinancialOverview(offlineFinancialOverview(tenant));setProtectionOverview(offlineProtectionOverview(tenant));setRepaymentOverview(buildOfflineRepaymentOverview(tenant,baseLedger));setLatestReplay(null);setAgentGateway(current=>({...current,connected:false,mode:'local-demo'}))}});return()=>{active=false}},[tenant,oidcReady]);
 useEffect(()=>{if(backendStatus!=='connected')return;let active=true;const refresh=()=>jobApi.queueHealth(tenant).then(queue=>{if(active)setQueueHealth(queue)}).catch(()=>{});const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer)}},[backendStatus,tenant]);
 useEffect(()=>{const fn=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(s=>!s)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='j'){e.preventDefault();setCopilotOpen(s=>!s)}if(e.key==='Escape'){setWorkspaceOpen(false);setMobileOpen(false);setNotificationOpen(false)}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)},[]);
 const addEvent=(caseId,title,detail,type='decision',meta={})=>setEvents(old=>[{id:'EV-'+Date.now(),tenant,time:'10:48:32',caseId,title,detail,type,runId:meta.runId||`RUN-${tenant.slice(-1)}-${caseId}`,stepId:meta.stepId||'STEP-04',actionId:meta.actionId||`ACTN-${String(Date.now()).slice(-4)}`,actor:meta.actor||'Hermes Agent',tool:meta.tool||'workflow.transition',status:meta.status||'已完成',version:meta.version||'FLOW v3.2',latency:meta.latency||'84 ms',cost:meta.cost||'¥0.02'},...old]);
 const openCase=(id,tab='概览')=>{const local=visibleCases.find(c=>c.case_id===id);if(!local&&backendStatus!=='connected')return;setCaseId(id);setCaseDetail(local||null);setCaseTab(tab);if(backendStatus==='connected')catalogApi.case(tenant,id).then(setCaseDetail).catch(error=>{setCaseId(null);notify(`案件详情读取失败：${error.message}`)})};
 const setActivityStatus=(ids,status)=>{const allowed=visibleActivities.filter(a=>ids.includes(a.id)&&!['blocked','completed'].includes(a.status));setActivities(old=>old.map(a=>allowed.some(x=>x.id===a.id)?{...a,status}:a));notify(allowed.length?`${allowed.length} 个活动已${status==='paused'?'暂停':'恢复模拟运行'}`:'当前选择包含保护暂停或已完成活动，无可操作项目')};
 const getPolicy=id=>{const authoritative=visiblePackages.find(item=>item.package_id===id&&item.serverAuthoritative);return policies[id]||(authoritative?{version:authoritative.policy_version,status:authoritative.policy_status,budget:authoritative.budget_limit_yuan,start:'09:00',end:'18:00',daily:1,weekly:3,retry:48,tone:'专业、温和、简洁',goal:'按服务端授权边界生成履约行动提案。',minSettlement:authoritative.min_settlement_bps/100,maxInstallments:authoritative.max_installments,minDownPayment:authoritative.min_down_payment_bps/100,offerValidity:7,approvalThreshold:75,evaluated:true}:{version:1,status:'published',budget:30,start:'09:00',end:'18:00',daily:1,weekly:3,retry:48,tone:'专业、温和、简洁',goal:'优先跟进已签协议的本期差额，到账后自动更新履约状态。',minSettlement:70,maxInstallments:6,minDownPayment:20,offerValidity:7,approvalThreshold:75,evaluated:true})};
 const savePolicy=(pkg,config)=>{if(backendStatus==='connected'){notify('在线模式未开放策略写接口，未修改服务端或浏览器状态');return}setPolicies(s=>({...s,[pkg]:{...config,version:getPolicy(pkg).version+1,status:config.status||'draft'}}));notify(`策略 v${getPolicy(pkg).version+1}.0 已保存为${config.status==='published'?'已发布版本':'草稿版本'}`);setDialog(null)};
 const advance=activity=>{const current=runSteps[activity.id]??2;setRunSteps(s=>({...s,[activity.id]:Math.min(3,current+1)}));addEvent(activity.caseIds[0],'补款跟进模拟完成','已进入等待回款阶段；尚未确认到账');notify('模拟跟进完成，进入等待支付状态')};
 const receive=async()=>{if(paid||receivingPayment)return;setReceivingPayment(true);try{if(backendStatus==='connected'){const accepted=await paymentApi.sandboxReceipt(tenant,'ui-demo-payment-v1');const payload=await paymentApi.overview(tenant);applyFinancialPayload(payload);setRepaymentOverview(await repaymentApi.overview(tenant));await refreshCatalog();setActivities(old=>old.map(a=>a.tenant===tenant&&a.caseIds.length===1&&a.caseIds[0]==='C002'?{...a,status:'completed',next:'本期已足额 · 下期 10.10',updated:'刚刚'}:a));addEvent('C002','本期补款已入账',`服务端 HMAC 验签、幂等、案件匹配、期次分摊与计佣完成；回执 ${accepted.receipt.id}`,'payment',{actor:'账务内核',tool:'payment.reconcile',version:'LEDGER v2',latency:'—',cost:'¥0.00'});setDialog(null);notify(accepted.duplicate?'该回执已处理，未重复入账':'服务端到账核验完成，期次、回款与佣金账簿已更新');return}setLedger(old=>[...old,{tenant_id:'TENANT_A',transaction_id:'DEMO-TX-001',case_id:'C002',package_id:'PKG_A',booked_date:'2026-09-12',event_type:'PAYMENT',cash_yuan:1016,eligible:true,eligible_cash_yuan:1016,rate:.15,commission_yuan:152.4,reason:'IN_MANDATE',commission_rule_id:'COM_A_V1',source:hostedDemo?'在线交互沙箱':'离线沙箱支付回调',signature:'沙箱验签通过',match_status:'已匹配',allocation:'PLAN002 · 第2期',idempotency:'首次接收'}]);setRepaymentOverview(old=>summarizeRepaymentPlans(old.plans.map(plan=>{if(plan.plan_id!=='PLAN002')return plan;const installments=plan.installments.map(row=>row.installment_no===2?{...row,paid_cents:row.due_cents,remaining_cents:0,status:'paid',last_payment_at:new Date().toISOString()}:row);const paid_cents=installments.reduce((sum,row)=>sum+row.paid_cents,0);return {...plan,installments,paid_cents,remaining_cents:plan.total_cents-paid_cents,overdue_cents:0}})));setPaid(true);setActivities(old=>old.map(a=>a.tenant==='TENANT_A'&&a.caseIds.length===1&&a.caseIds[0]==='C002'?{...a,status:'completed',next:'本期已足额 · 下期 10.10',updated:'10:48'}:a));addEvent('C002','本期补款已入账',`${hostedDemo?'在线':'离线'}演示完成验签、去重、匹配、期次分摊与计佣；未写入服务端账簿`,'payment',{actor:'演示账务接口',tool:'payment.reconcile',version:'DEMO v2',latency:'326 ms',cost:'¥0.00'});setDialog(null);notify(`${hostedDemo?'在线':'离线'}演示到账完成；未写入服务端账簿`)}catch(error){notify(`支付回执处理失败：${error.message}`)}finally{setReceivingPayment(false)}};
 const reconciliationCandidates=async receipt=>backendStatus==='connected'?paymentApi.matchCandidates(tenant,receipt.id):visibleCases.slice(0,5).map(c=>{const signed=['active','completed'].includes(c.governedPlan?.status)||c.plan?.status==='SIGNED';return {case_id:c.case_id,package_id:c.package_id,score:(signed?40:20)+(c.blocked?0:5),signals:['当前租户财务档案完整',signed?'存在已签履约方案':'无已签方案',c.blocked?'保护状态：仅允许被动到账核对':'案件未处于保护暂停'],blocked:c.blocked,has_signed_plan:signed}}).sort((x,y)=>y.score-x.score||x.case_id.localeCompare(y.case_id));
 const createReconciliationSample=async()=>{if(backendStatus!=='connected'){notify('离线演示已包含一条待独立复核的样本回执');return}const key=`review-demo-${Date.now()}`;await paymentApi.sandboxReceipt(tenant,key,{caseId:'C999',amountCents:68800});applyFinancialPayload(await paymentApi.overview(tenant));notify('已生成一条验签通过但案件未匹配的沙箱回执')};
 const proposeReceiptReconciliation=async(receipt,caseId,reason)=>{if(backendStatus==='connected'){const review=await paymentApi.proposeReconciliation(tenant,receipt.id,caseId,reason);applyFinancialPayload(await paymentApi.overview(tenant));notify('匹配提案已提交，等待另一名管理员复核');return review}const candidates=await reconciliationCandidates(receipt);const review={id:`REC-DEMO-${Date.now()}`,receipt_id:receipt.id,proposed_case_id:caseId,candidate_snapshot:candidates,evidence_digest:`demo-${Date.now()}`,reason,status:'pending_review',version:1,proposed_by:identity.actor_id,proposed_at:new Date().toISOString(),reviewed_by:null,reviewed_at:null,review_note:null,recovery_entry_id:null};setFinancialOverview(old=>({...old,pendingReceipts:old.pendingReceipts.map(row=>row.id===receipt.id?{...row,status:'review_pending',failure_code:'human_review_pending'}:row),reconciliations:[review,...old.reconciliations.filter(row=>row.receipt_id!==receipt.id)]}));notify('演示匹配提案已提交；需要另一名管理员复核');return review};
 const decideReceiptReconciliation=async(review,decision,note)=>{if(identity.role!=='admin')throw new Error('仅管理员可以复核对账提案');if(review.proposed_by===identity.actor_id)throw new Error('提案人与复核人必须是不同账号');if(backendStatus==='connected'){const decided=await paymentApi.decideReconciliation(tenant,review.id,decision,note,review.version);applyFinancialPayload(await paymentApi.overview(tenant));notify(decision==='approve'?'复核已批准，回款与佣金账簿已原子更新':'复核已驳回，回执未进入钱指标');return decided}const receipt=financialOverview.pendingReceipts.find(row=>row.id===review.receipt_id);if(!receipt)throw new Error('待复核回执不存在');const reviewed={...review,status:decision==='approve'?'approved':'rejected',version:review.version+1,reviewed_by:identity.actor_id,reviewed_at:new Date().toISOString(),review_note:note,recovery_entry_id:decision==='approve'?`demo-review:${receipt.provider_event_id}`:null};if(decision==='approve'){const selected=visibleCases.find(c=>c.case_id===review.proposed_case_id);const rate=visiblePackages.find(p=>p.package_id===selected?.package_id)?.rate||0;const amount=receipt.amount_cents/100;const commission=Math.round(receipt.amount_cents*rate)/100;setLedger(old=>old.some(row=>row.transaction_id===reviewed.recovery_entry_id)?old:[...old,{tenant_id:tenant,transaction_id:reviewed.recovery_entry_id,receipt_id:receipt.id,case_id:review.proposed_case_id,package_id:selected?.package_id||'—',booked_date:receipt.occurred_at.slice(0,10),event_type:'PAYMENT',cash_yuan:amount,eligible:true,eligible_cash_yuan:amount,rate,commission_yuan:commission,reason:'IN_MANDATE',commission_rule_id:`DEMO-${selected?.package_id||'RULE'}`,source:'离线双人复核演示',signature:'HMAC v1 摘要已核验',match_status:'已匹配',allocation:`${review.proposed_case_id} · 人工复核匹配`,idempotency:'Provider 事件唯一'}]);addEvent(review.proposed_case_id,'人工对账复核已批准',`回执 ${receipt.provider_event_id} 通过双人复核；当前为浏览器演示事件`,'payment',{actor:identity.display_name,tool:'payment.reconciliation.approve',version:'RECON v1',cost:'¥0.00'})}setFinancialOverview(old=>{const summary=old.summary?{...old.summary,pending_receipt_count:Math.max(0,old.summary.pending_receipt_count-1)}:null;if(decision==='approve'&&summary){const rate=visiblePackages.find(p=>p.package_id===visibleCases.find(c=>c.case_id===review.proposed_case_id)?.package_id)?.rate||0;const commission=Math.round(receipt.amount_cents*rate);summary.confirmed_net_recovery_cents+=receipt.amount_cents;summary.commission_eligible_recovery_cents+=receipt.amount_cents;summary.accrued_commission_cents+=commission;summary.unsettled_commission_cents+=commission}return {...old,summary,pendingReceipts:old.pendingReceipts.filter(row=>row.id!==receipt.id),reconciliations:old.reconciliations.map(row=>row.id===review.id?reviewed:row)}});notify(decision==='approve'?'演示复核已批准；未写入服务端账簿':'演示复核已驳回；未更新钱指标');return reviewed};
 const proposeProtectionResolution=async(incident,note,evidenceRefs)=>{if(incident.release_policy==='permanent_hold')throw new Error('停止联系保护不能通过通用异常流程解除');if(backendStatus==='connected'){const proposed=await protectionApi.proposeResolution(tenant,incident.id,note,evidenceRefs);setProtectionOverview(await protectionApi.overview(tenant));notify('解除提案已提交，保护状态继续生效，等待独立管理员复核');return proposed}const refs=[...new Set(evidenceRefs.map(value=>value.trim().toUpperCase()).filter(Boolean))].sort();if(incident.release_policy==='renewal_evidence'&&!refs.some(value=>value.startsWith('MANDATE-')))throw new Error('委托到期保护需要 MANDATE- 开头的续期授权证据');const proposed={...incident,status:'pending_review',version:incident.version+1,resolution_note:note,evidence_refs:refs,evidence_digest:`demo-evidence-${Date.now()}`,proposed_by:identity.actor_id,proposed_at:new Date().toISOString(),reviewed_by:null,reviewed_at:null,review_note:null,case_released:false};setProtectionOverview(old=>summarizeProtection(old.incidents.map(row=>row.id===incident.id?proposed:row)));notify('演示解除提案已提交；保护状态仍然生效');return proposed};
 const decideProtectionResolution=async(incident,decision,note)=>{if(identity.role!=='admin')throw new Error('仅管理员可以复核保护解除提案');if(incident.proposed_by===identity.actor_id)throw new Error('提案人与复核人必须是不同账号');if(backendStatus==='connected'){const decided=await protectionApi.decideResolution(tenant,incident.id,decision,note,incident.version);setProtectionOverview(await protectionApi.overview(tenant));await refreshCatalog();if(decided.case_released)setExceptionResolutions(old=>({...old,[incident.case_id]:{status:'resolved',time:new Date().toISOString()}}));addEvent(incident.case_id,decision==='approve'?'保护解除提案已批准':'保护解除提案已驳回',decided.case_released?'案件进入待重新评估，原活动不会自动恢复':'案件继续保持保护暂停','exception',{actor:identity.display_name,tool:`protection.resolution.${decision}`,version:`GUARD v${decided.version}`});notify(decision==='approve'?(decided.case_released?'复核通过；案件已解除阻断并等待重新评估':'复核通过；案件仍有其他保护事件'):'复核已驳回；案件继续保持保护');return decided}const activeOthers=protectionOverview.incidents.some(row=>row.id!==incident.id&&row.case_id===incident.case_id&&protectionActiveStatuses.includes(row.status));const released=decision==='approve'&&!activeOthers;const decided={...incident,status:decision==='approve'?'resolved':'open',version:incident.version+1,reviewed_by:identity.actor_id,reviewed_at:new Date().toISOString(),review_note:note,resolved_at:decision==='approve'?new Date().toISOString():null,case_released:released};setProtectionOverview(old=>summarizeProtection(old.incidents.map(row=>row.id===incident.id?decided:row)));if(released)setExceptionResolutions(old=>({...old,[incident.case_id]:{status:'resolved',time:new Date().toISOString()}}));addEvent(incident.case_id,decision==='approve'?'保护解除提案已批准':'保护解除提案已驳回',released?'案件进入待重新评估；原活动不会自动恢复':'案件继续保持保护暂停','exception',{actor:identity.display_name,tool:`protection.resolution.${decision}`,version:`GUARD v${decided.version}`,cost:'¥0.00'});notify(decision==='approve'?(released?'演示复核通过；案件等待重新评估':'演示复核通过；仍有其他保护事件'):'演示复核驳回；保护继续生效');return decided};
 const proposeRepaymentPlan=async form=>{const selected=visibleCases.find(row=>row.case_id===form.caseId);if(!selected)throw new Error('案件不存在或不属于当前工作空间');const policy=getPolicy(selected.package_id);const claimCents=Math.round(selected.transfer_balance_yuan*100);const totalCents=Math.round(Number(form.total)*100);const downCents=Math.round(Number(form.down)*100);const count=Number(form.count);const agreementDigest=form.agreementDigest.trim().toLowerCase();if(!/^[0-9a-f]{64}$/.test(agreementDigest))throw new Error('请输入外部签约系统返回的 64 位 SHA-256 摘要');if(totalCents>claimCents)throw new Error('方案总额不能超过已核验债权余额');if(totalCents*100<claimCents*policy.minSettlement)throw new Error('方案总额低于当前资产包最低结算比例');if(downCents>totalCents||downCents*100<totalCents*policy.minDownPayment)throw new Error('首期金额不满足当前资产包最低首付比例');if(count<1||count>policy.maxInstallments)throw new Error('分期期数超过当前资产包策略上限');if(count===1&&downCents!==totalCents)throw new Error('单期方案的首期金额必须等于方案总额');const installments=buildInstallments(totalCents,downCents,count,form.firstDue);const planId=`PLAN-${form.caseId}-${Date.now().toString().slice(-8)}`;const payload={plan_id:planId,total_cents:totalCents,down_payment_cents:downCents,installments,agreement_reference:form.agreementReference.trim().toUpperCase(),agreement_digest:agreementDigest,signed_at:new Date().toISOString(),proposal_reason:form.reason.trim()};if(backendStatus==='connected'){const plan=await repaymentApi.propose(tenant,form.caseId,payload);setRepaymentOverview(await repaymentApi.overview(tenant));notify('签约方案已提交；批准前不会改变案件或期次余额');return plan}const plan={id:`DEMO-RPLAN-${Date.now()}`,...payload,case_id:form.caseId,status:'pending_review',version:1,currency:'CNY',claim_balance_cents:claimCents,installment_count:count,policy_version:policy.version,policy_snapshot:{min_settlement_bps:policy.minSettlement*100,max_installments:policy.maxInstallments,min_down_payment_bps:policy.minDownPayment*100},evidence_digest:agreementDigest,proposal_reason:payload.proposal_reason,proposed_by:identity.actor_id,proposed_at:new Date().toISOString(),reviewed_by:null,reviewed_at:null,review_note:null,activated_at:null,completed_at:null,paid_cents:0,remaining_cents:totalCents,overdue_cents:0,installments:installments.map(row=>({...row,installment_id:`${planId}-${String(row.installment_no).padStart(2,'0')}`,paid_cents:0,remaining_cents:row.due_cents,status:'scheduled',last_payment_at:null}))};setRepaymentOverview(old=>summarizeRepaymentPlans([plan,...old.plans]));notify('演示签约提案已提交；未写入服务端');return plan};
 const decideRepaymentPlan=async(plan,decision,note)=>{if(identity.role!=='admin')throw new Error('仅管理员可以复核签约方案');if(plan.proposed_by===identity.actor_id)throw new Error('提案人与复核人必须是不同账号');if(backendStatus==='connected'){const decided=await repaymentApi.decide(tenant,plan.id,decision,note,plan.version);setRepaymentOverview(await repaymentApi.overview(tenant));await refreshCatalog();addEvent(plan.case_id,decision==='approve'?'签约方案已激活':'签约方案已驳回',decision==='approve'?'签署摘要和条款通过独立复核；等待验签回款分摊':'方案未生效，案件状态和资金事实未改变','plan',{actor:identity.display_name,tool:`repayment_plan.${decision}`,version:`PLAN v${decided.version}`,cost:'¥0.00'});notify(decision==='approve'?'方案已激活；仅验签回款能够减少期次余额':'方案已驳回；案件和资金状态未改变');return decided}const decided={...plan,status:decision==='approve'?'active':'rejected',version:plan.version+1,reviewed_by:identity.actor_id,reviewed_at:new Date().toISOString(),review_note:note,activated_at:decision==='approve'?new Date().toISOString():null};setRepaymentOverview(old=>summarizeRepaymentPlans(old.plans.map(row=>row.id===plan.id?decided:row)));notify(decision==='approve'?'演示方案已激活；未写入服务端':'演示方案已驳回');return decided};
 const switchTenant=id=>{setTenant(id);setScope('all');setCaseId(null);setCaseDetail(null);setDialog(null);setWorkspaceOpen(false);navigate('activities');notify(`已切换至${organization[id]}`)};
 const serviceConfigs=serviceConfigsByTenant[tenant];
 const integrationState=integrationStatesByTenant[tenant];
 const integrationReadiness=integrationGate(serviceConfigs,integrationState);
 const reset=async()=>{setActivities(initialActivities);setEvents(initialEvents);setRunSteps({});setPolicies({});setServiceConfigsByTenant(makeInitialServiceConfigs());setIntegrationStatesByTenant(makeInitialIntegrationStates());setExceptionResolutions({});setCopilotOpen(false);setDialog(null);setScope('all');setReceivingPayment(false);if(backendStatus==='connected'){try{applyFinancialPayload(await paymentApi.overview(tenant));setProtectionOverview(await protectionApi.overview(tenant));setRepaymentOverview(await repaymentApi.overview(tenant));await refreshCatalog()}catch{notify('演示状态已还原，但服务端状态刷新失败');navigate('activities');return}}else{setLedger(baseLedger);setPaid(false);setFinancialOverview(offlineFinancialOverview(tenant));setProtectionOverview(offlineProtectionOverview(tenant));setRepaymentOverview(buildOfflineRepaymentOverview(tenant,baseLedger))}navigate('activities');notify(backendStatus==='connected'?'演示状态已还原；服务端业务状态保持不变':'离线演示数据已还原')};
 const createActivity=async form=>{const p=getPolicy(form.package);let remote=null;if(backendStatus==='connected'){try{remote=await activityApi.create(tenant,form)}catch(error){notify(`活动创建失败：${error.message}`);return}}const id=remote?.activity_id||'ACT-'+String(activities.length+1).padStart(3,'0');const {productionReady,mode:localMode}=determineActivityMode({integrationReady:integrationReadiness.ready,policyStatus:p.status,caseCount:form.caseIds.length});const mode=remote?.mode||localMode;const versions=serviceVersionSnapshot(serviceConfigs);const rawSnapshot=remote?.service_snapshot;const snapshot=rawSnapshot?{agent:`${rawSnapshot.agent?.provider||'—'} · ${rawSnapshot.agent?.settings?.profile||'—'} · v${rawSnapshot.agent?.version||'—'}`,model:`${rawSnapshot.model?.provider||'—'} · ${rawSnapshot.model?.settings?.model||'—'} · v${rawSnapshot.model?.version||'—'}`,voice:`${rawSnapshot.voice?.provider||'—'} · ${rawSnapshot.voice?.settings?.tts||'—'} · v${rawSnapshot.voice?.version||'—'}`,phone:`${rawSnapshot.phone?.provider||'—'} · ${rawSnapshot.phone?.settings?.callerId||'—'} · v${rawSnapshot.phone?.version||'—'}`,selfTest:rawSnapshot.self_test_id||'未使用',enabledAt:integrationState.enabledAt||'未启用'}:{agent:`${serviceConfigs.agent.provider} · ${serviceConfigs.agent.profile} · v${versions.agent}`,model:`${serviceConfigs.model.provider} · ${serviceConfigs.model.model} · v${versions.model}`,voice:`${serviceConfigs.voice.provider} · ${serviceConfigs.voice.tts} · v${versions.voice}`,phone:`${serviceConfigs.phone.provider} · ${serviceConfigs.phone.callerId} · v${versions.phone}`,selfTest:productionReady?integrationState.lastRun?.id:'未使用',enabledAt:productionReady?integrationState.enabledAt:'未启用'};const caseIds=remote?.case_ids||form.caseIds;const entry={id,tenant,name:remote?.name||form.name,package:remote?.package_id||form.package,caseIds,status:remote?.status||'running',goal:remote?.goal||form.goal,next:mode==='sandbox'?'沙箱计划已生成 · 不触达真实号码':'预检通过 · 等待执行窗口',updated:'刚刚',version:remote?.policy_version||p.version,policy:{...p},budget:Number(remote?.budget_yuan||form.budget),mode,serviceSnapshot:snapshot,preflight:remote?.preflight||{mandate:true,policy:p.status==='published',caseScope:caseIds.length>0,channel:productionReady,channelChecks:{...integrationReadiness}}};setActivities(old=>[entry,...old.filter(item=>item.id!==id)]);setRunSteps(s=>({...s,[id]:1}));addEvent(caseIds[0],'活动已创建',`${entry.name} · ${caseIds.length} 个案件 · ${mode==='sandbox'?'纯模拟':'已启用渠道'} · ${backendStatus==='connected'?'后端预检已确认':'本地演示预检'}`,'decision',{runId:`RUN-${id}-${caseIds[0]}`,stepId:'STEP-01',tool:'campaign.preflight',version:`POL v${entry.version}.0`});setDialog(null);navigate('agents/'+id);notify(`活动已创建，${serviceConfigs.agent.provider} 进入${mode==='sandbox'?'纯模拟':'授权'}运行`)};
 const updateServiceConfig=(service,config)=>{
  const safeConfig=sanitizeServiceConfig(service,config);
  setServiceConfigsByTenant(all=>{const current=all[tenant][service];return {...all,[tenant]:{...all[tenant],[service]:{...current,...safeConfig,version:Number(current.version||0)+1,updatedAt:formatNow()}}}});
  setIntegrationStatesByTenant(all=>({...all,[tenant]:{...all[tenant],enabled:false,lastRun:null,enabledAt:null,enabledBy:null,enabledServiceVersions:null,invalidatedReason:`${service} 配置已变更，需重新完成连接测试与沙箱自测`}}));
 };
 const updateIntegrationState=patch=>setIntegrationStatesByTenant(all=>({...all,[tenant]:{...all[tenant],...patch}}));
 const applyRemoteOverview=payload=>{const normalized=normalizeIntegrationOverview(payload);setServiceConfigsByTenant(all=>({...all,[tenant]:{...all[tenant],...normalized.services}}));setIntegrationStatesByTenant(all=>({...all,[tenant]:normalized.state}));return normalized};
 const refreshAgentGateway=async()=>{const gateway=await agentApi.gateway(tenant);setAgentGateway(gateway);agentSessions.current=Object.fromEntries(Object.entries(agentSessions.current).filter(([key])=>!key.startsWith(`${tenant}:`)));return gateway};
 const refreshModelGateway=async()=>{const health=await securityApi.modelGatewayHealth(tenant);setModelGateway(health);return health};
 const saveServiceConfig=async(service,config)=>{if(backendStatus!=='connected'){updateServiceConfig(service,{...config,saved:true,tested:false,latency:'—'});if(service==='agent'){setAgentGateway(current=>({...current,provider:config.provider,profile:config.profile,transport:config.transport||'sandbox-contract',session_persistence:config.sessionPersistence||'database-checkpoint',connected:false}));agentSessions.current=Object.fromEntries(Object.entries(agentSessions.current).filter(([key])=>!key.startsWith(`${tenant}:`)))}return null}const payload=await integrationApi.save(tenant,service,config);const normalized=applyRemoteOverview(payload);if(service==='agent')await refreshAgentGateway();if(service==='model')await refreshModelGateway();return normalized};
 const testServiceConnection=async(service,config)=>{if(backendStatus!=='connected'){const latency=service==='agent'?'126 ms':service==='model'?'72 ms':service==='voice'?'236 ms':'41 ms';updateServiceConfig(service,{...config,saved:true,tested:true,latency});if(service==='agent'){setAgentGateway(current=>({...current,provider:config.provider,profile:config.profile,transport:config.transport||'sandbox-contract',session_persistence:config.sessionPersistence||'database-checkpoint',connected:true}));agentSessions.current=Object.fromEntries(Object.entries(agentSessions.current).filter(([key])=>!key.startsWith(`${tenant}:`)))}return null}await integrationApi.save(tenant,service,config);await integrationApi.test(tenant,service,setActiveJob);const normalized=applyRemoteOverview(await integrationApi.get(tenant));if(service==='agent')await refreshAgentGateway();if(service==='model')await refreshModelGateway();return normalized};
 const runIntegrationSelfTest=async()=>{if(backendStatus!=='connected')return null;await integrationApi.selfTest(tenant,setActiveJob);return applyRemoteOverview(await integrationApi.get(tenant)).state.lastRun};
 const enableIntegration=async()=>{if(backendStatus!=='connected'){updateIntegrationState({enabled:true,enabledAt:formatNow(),enabledBy:'Terry',enabledServiceVersions:serviceVersionSnapshot(serviceConfigs),invalidatedReason:null});return null}return applyRemoteOverview(await integrationApi.enable(tenant))};
 const preflightActivity=async form=>backendStatus==='connected'?activityApi.preflight(tenant,form):null;
 const askAgent=async(content,scope={})=>{if(backendStatus!=='connected')return null;const scopeType=scope.scopeType||'global';const scopeId=scope.scopeId||null;const key=`${tenant}:${scopeType}:${scopeId||'root'}`;let sessionId=agentSessions.current[key];if(!sessionId){const session=await agentApi.createSession(tenant,{scopeType,scopeId,title:scope.title||`${PRODUCT_NAME} 会话`});sessionId=session.id;agentSessions.current[key]=sessionId}const job=await agentApi.message(tenant,sessionId,content,setActiveJob);return {...job.result,session_id:sessionId}};
 const confirmAgentProposal=async proposalId=>{if(backendStatus!=='connected')return null;const result=await agentApi.confirmProposal(tenant,proposalId);return result};
 const runModelReplay=async(mode='deterministic-contract')=>{if(backendStatus!=='connected')return null;const job=await agentApi.replay(tenant,mode,setActiveJob);const replay=await agentApi.replayRun(tenant,job.result.replay_run_id);setLatestReplay(replay);return replay};
 const queueLabel=backendStatus==='auth-required'?'需要企业身份':backendStatus==='api-error'?'API 配置异常':backendStatus!=='connected'?(hostedDemo?'在线演示 · API 未接入':'离线演示 · 本地运行'):queueHealth.mode==='external'?(queueHealth.status==='healthy'?'独立 Worker · 持久运行':'Worker 降级 · 作业保留'):'API 内联 · 持久作业';
 const a={tenant,theme,setTheme,route,page,navigate,activities,visibleActivities,cases,visibleCases,packages,visiblePackages,catalogTotals,catalogRevision,refreshCatalog,ledger,visibleLedger,events,paid,receivingPayment,financialOverview,protectionOverview,repaymentOverview,scope,setScope,dialog,setDialog,openCase,notify,setActivityStatus,getPolicy,savePolicy,runSteps,advance,receive,reconciliationCandidates,createReconciliationSample,proposeReceiptReconciliation,decideReceiptReconciliation,proposeProtectionResolution,decideProtectionResolution,proposeRepaymentPlan,decideRepaymentPlan,createActivity,preflightActivity,organization,setOrganization,notificationPreferences,setNotificationPreferences,serviceConfigs,integrationState,integrationReadiness,backendStatus,hostedDemo,identity,agentGateway,modelGateway,queueHealth,secretHealth,authHealth,latestReplay,activeJob,askAgent,confirmAgentProposal,runModelReplay,updateServiceConfig,updateIntegrationState,saveServiceConfig,testServiceConnection,runIntegrationSelfTest,enableIntegration,reset,copilotOpen,setCopilotOpen,exceptionResolutions,setExceptionResolutions,addEvent};
 const activeCaseBase=caseDetail?.case_id===caseId?caseDetail:visibleCases.find(c=>c.case_id===caseId);
 const activeCase=activeCaseBase?{...activeCaseBase,governedPlan:repaymentOverview.plans.find(plan=>plan.case_id===activeCaseBase.case_id&&['pending_review','active','completed'].includes(plan.status))}:null;
 const activeRepaymentPlan=dialog?.type==='plan-review'?repaymentOverview.plans.find(plan=>plan.id===dialog.planId):null;
 const results=search.trim()?visibleCases.filter(c=>(c.case_id+' '+c.package_id+' '+c.status).toLowerCase().includes(search.toLowerCase())).slice(0,5):[];
 const acts=search.trim()?visibleActivities.filter(x=>(x.name+x.id).toLowerCase().includes(search.toLowerCase())).slice(0,3):[];
 if(backendStatus==='auth-required'||backendStatus==='api-error')return <main className="startup-blocked"><section><ShieldCheck size={34}/><span className="eyebrow">REPAYGUARD STARTUP GATE</span><h1>{backendStatus==='auth-required'?'需要企业身份':'业务 API 尚未就绪'}</h1><p>{backendStatus==='auth-required'?'API 已响应，但当前会话没有有效身份或工作空间权限。系统不会把认证失败降级成可写的本地演示。':backendError}</p><div className="notice">请完成企业 SSO 登录或修复服务端配置后重新加载。当前未执行任何业务写入。</div><div className="footer-actions">{backendStatus==='auth-required'&&oidcConfigured()&&<Button variant="primary" onClick={()=>beginOidcLogin().catch(error=>setBackendError(error.message))}>企业 SSO 登录</Button>}<Button onClick={()=>window.location.reload()}>重新检查</Button></div></section></main>;
 return <AppContext.Provider value={a}><div className={`app-shell ${mobileOpen?'mobile-open':''}`}>
 <aside className="sidebar"><button className="brand" onClick={()=>navigate('overview')}><img src={BRAND_ASSET} alt={`${PRODUCT_NAME} 标志`}/><span><strong>{PRODUCT_NAME}</strong><small>{PRODUCT_ENGLISH_NAME} · {PRODUCT_DESCRIPTOR}</small></span></button>
 <div className="workspace-area"><button className="workspace-switch" aria-expanded={workspaceOpen} onClick={()=>setWorkspaceOpen(!workspaceOpen)}><Buildings size={21}/><span><b>{organization[tenant]}</b><small>资产履约工作空间</small></span><CaretDown size={14}/></button>{workspaceOpen&&<div className="workspace-pop"><span className="overline">切换工作空间</span>{['TENANT_A','TENANT_B'].map(id=><button key={id} onClick={()=>switchTenant(id)}><Buildings size={17}/>{organization[id]}{tenant===id&&<CheckCircle size={17}/>}</button>)}</div>}</div>
 <button className="sidebar-search" onClick={()=>{setSearch('');setNotificationOpen(false);setSearchOpen(true)}}><MagnifyingGlass size={18}/><span>快速搜索</span><kbd>⌘ K</kbd></button>
 <nav>{nav.map(([id,Icon])=><React.Fragment key={id}>{id==='agents'&&<div className="nav-label">AI 运营</div>}<button className={page===id?'nav-item active':'nav-item'} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={20}/><span>{titles[id]}</span>{id==='activities'&&<small>{visibleActivities.filter(x=>x.status==='running').length}</small>}{id==='plans'&&repaymentOverview.pending_review_count>0&&<small>{repaymentOverview.pending_review_count}</small>}{id==='exceptions'&&protectedCount>0&&<small>{protectedCount}</small>}</button></React.Fragment>)}</nav>
 <div className="sidebar-bottom"><div className="simulation-status"><span className={backendStatus==='connected'&&queueHealth.status==='degraded'?'warning-dot':'live-dot'}/>{queueLabel}</div><button className={`nav-item ${page==='usage'?'active':''}`} onClick={()=>navigate('usage')}><Receipt size={20}/>用量与账单</button><button className={`nav-item ${page==='settings'?'active':''}`} onClick={()=>navigate('settings')}><GearSix size={20}/>组织设置</button><div className="profile"><span className="avatar">{identity.display_name?.slice(0,1)||'T'}</span><span>{identity.display_name}<small>{identity.role==='admin'?'工作空间管理员':identity.role==='operator'?'运营人员':'观察员'} · {identity.auth_mode==='oidc'?'OIDC':'开发身份'}</small></span><span className="plan-tag">Team</span></div></div></aside>
 <div className="main-shell"><header className="topbar"><IconButton icon={List} label="打开导航" className="mobile-menu icon-btn" onClick={()=>setMobileOpen(!mobileOpen)}/><div className="breadcrumb"><span>工作空间</span><span>/</span><b>{titles[page]||'履约活动'}</b>{route.includes('/')&&<><span>/</span><span>运行详情</span></>}</div><div className="top-actions"><button className="global-search mobile-search" onClick={()=>{setSearch('');setNotificationOpen(false);setSearchOpen(true)}}><MagnifyingGlass size={17}/><span>搜索案件、活动或功能…</span><kbd>⌘ K</kbd></button><button className="top-ai-button" onClick={()=>setCopilotOpen(true)}><Robot size={16}/><span>AI 查询</span><kbd>⌘ J</kbd></button><span className={`demo-tag ${backendStatus==='connected'?'server-connected':''}`}>{backendStatus==='connected'?`API v${APP_VERSION}`:hostedDemo?'在线演示':'演示'}</span><div className="notification-wrap"><button className="icon-btn notification-trigger" aria-label="打开通知中心" aria-expanded={notificationOpen} onClick={()=>setNotificationOpen(!notificationOpen)}><Bell size={19}/>{!notificationsRead&&<span className="notification-count">3</span>}</button>{notificationOpen&&<section className="notification-pop" aria-label="通知中心"><header><div><b>通知中心</b><small>AI 运行与账务提醒</small></div><button className="text-link small" onClick={()=>setNotificationsRead(true)}>全部已读</button></header><button onClick={()=>navigate('exceptions')}><span className="notification-icon warning"><ShieldCheck size={18}/></span><span><b>{protectedCount} 个案件已保护暂停</b><small>争议、停止联系或授权异常已阻断触达</small></span></button><button onClick={()=>navigate('plans')}><span className="notification-icon"><CalendarCheck size={18}/></span><span><b>{repaymentOverview.pending_review_count} 个签约方案等待复核</b><small>独立批准后才进入履约，回款才减少期次余额</small></span></button><button onClick={()=>navigate('payments')}><span className="notification-icon"><CurrencyCircleDollar size={18}/></span><span><b>{financialOverview.summary?.pending_receipt_count||0} 笔回执等待复核</b><small>核验后才会更新履约与应计佣金</small></span></button></section>}</div><IconButton icon={theme==='light'?Moon:Sun} label={theme==='light'?'切换深色主题':'切换浅色主题'} onClick={()=>setTheme(theme==='light'?'dark':'light')}/><IconButton icon={Question} label="交互指南" onClick={()=>setDialog({type:'help'})}/><button className="avatar top-avatar" aria-label="打开个人设置" onClick={()=>identity.auth_mode==='oidc'?logoutOidc():navigate('settings')}>{identity.display_name?.slice(0,1)||'T'}</button></div></header>
 <main className="main-content" key={`${tenant}-${page}`}>{page==='overview'?<Overview/>:page==='activities'?<Activities/>:page==='assets'?<Assets/>:page==='cases'?<Cases/>:page==='plans'?<RepaymentPlans/>:page==='payments'?<Payments/>:page==='agents'?<AgentScreen/>:page==='exceptions'?<Exceptions/>:page==='logs'?<Logs/>:page==='strategy'?<Strategy/>:page==='integrations'?<Integrations/>:page==='usage'?<Usage/>:page==='settings'?<Settings/>:<Activities/>}</main></div>
 {activeCase&&<CaseDrawer c={activeCase} tab={caseTab} setTab={setCaseTab} onClose={()=>setCaseId(null)}/>}
 {dialog?.type==='create'&&<CreateWizard defaultPackage={dialog.package} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='policy'&&visiblePackages.length>0&&<PolicyModal packageId={dialog.package||visiblePackages[0].package_id} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='receipt'&&tenant==='TENANT_A'&&<ReceiptModal onClose={()=>setDialog(null)}/>}
 {dialog?.type==='payment'&&dialog.transaction&&<PaymentDetailModal transaction={dialog.transaction} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='reconciliation'&&dialog.receipt&&<ReconciliationModal receipt={dialog.receipt} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='exception'&&<ExceptionModal incidentId={dialog.incidentId} caseId={dialog.caseId} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='plan-create'&&<RepaymentPlanCreateModal onClose={()=>setDialog(null)}/>}
 {dialog?.type==='plan-review'&&activeRepaymentPlan&&<RepaymentPlanReviewModal plan={activeRepaymentPlan} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='import'&&<ImportModal onClose={()=>setDialog(null)}/>}
 {dialog?.type==='help'&&<Modal title="体验一条完整的资产履约流程" subtitle="当前 Provider 与业务数据均为沙箱样本，可随时还原。" onClose={()=>setDialog(null)} footer={<Button variant="primary" onClick={()=>{setDialog(null);navigate('activities')}}>开始体验 <ArrowRight size={16}/></Button>}><ol className="guide"><li><b>完成 AI 与渠道接入</b><p>分别配置 Agent、模型、语音和电话，完成连接、自测与启用。</p></li><li><b>创建履约活动</b><p>选择资产包与目标，由后端重新预检并冻结服务快照。</p></li><li><b>查看 Agent 执行</b><p>查看运行阶段、判断依据和下一步，体验暂停与恢复。</p></li><li><b>核对到账与佣金</b><p>模拟 ¥1,016 到账，观察履约、回款和应计佣金联动。</p></li></ol><div className="notice">API 已连接时配置与门禁写入后端；离线时明确降级为浏览器演示。两种模式都不保存明文凭证，也不会发起真实外呼或支付。</div></Modal>}
 {dialog?.type==='reset'&&<Modal title="还原演示数据" subtitle="将清除本次会话内创建的活动、策略修改和模拟到账。" onClose={()=>setDialog(null)} footer={<><Button onClick={()=>setDialog(null)}>取消</Button><Button variant="primary" onClick={reset}>还原演示</Button></>}><p>还原后回到最初的样本状态。此操作仅影响当前原型。</p></Modal>}
 {searchOpen&&<Modal title="搜索工作空间" onClose={()=>setSearchOpen(false)}><Search value={search} onChange={setSearch} placeholder="输入案件编号、活动名称或功能…"/><div className="command-results">{!search&&<p className="muted small">快速跳转</p>}{Object.entries(titles).filter(([,v])=>!search||v.toLowerCase().includes(search.toLowerCase())).slice(0,search?10:5).map(([id,v])=><button key={id} onClick={()=>{navigate(id);setSearchOpen(false)}}><Command size={17}/><span>{v}</span><ArrowRight size={16}/></button>)}{results.map(c=><button key={c.case_id} onClick={()=>{setSearchOpen(false);openCase(c.case_id)}}><Files size={17}/><span>{c.case_id} · {c.status}</span><small>{c.package_id}</small></button>)}{acts.map(x=><button key={x.id} onClick={()=>{navigate('agents/'+x.id);setSearchOpen(false)}}><Robot size={17}/><span>{x.name}</span><ArrowRight size={16}/></button>)}{search&&!results.length&&!acts.length&&!Object.values(titles).some(v=>v.toLowerCase().includes(search.toLowerCase()))&&<Empty/>}</div><p className="muted small">仅搜索当前组织的数据 · 按 Esc 关闭</p></Modal>}
 <AICopilot/>
 {toast&&<div className="toast" role="status"><CheckCircle size={20} weight="fill"/><span>{toast}</span><IconButton icon={X} label="关闭提示" onClick={()=>setToast('')}/></div>}
 </div></AppContext.Provider>
}
