import React,{useEffect,useRef,useState} from 'react';
import {CheckCircle,WarningCircle,DownloadSimple} from '@phosphor-icons/react';
import {operationsApi} from './api';
import {Button,Field,KeyValue} from './ui';

export function CaseValidation({tenant,connected}){
 const [caseId,setCaseId]=useState(''),[report,setReport]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const sequence=useRef(0);
 useEffect(()=>{sequence.current++;setCaseId('');setReport(null);setError('');setBusy(false);return()=>{sequence.current++}},[tenant,connected]);
 const inspect=async e=>{e.preventDefault();const current=++sequence.current;setBusy(true);setError('');setReport(null);try{const result=await operationsApi.caseValidation(tenant,caseId.trim());if(current===sequence.current)setReport(result)}catch(err){if(current===sequence.current)setError(err.message)}finally{if(current===sequence.current)setBusy(false)}};
 const download=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='case-validation-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section className="case-validation dashboard-card"><div className="section-title"><h2>真实案例证据核对</h2>{report&&<Button icon={DownloadSimple} onClick={download}>下载报告</Button>}</div><p className="muted">选择已导入的脱敏案件，核对来源、委托、策略、保护状态和回款证据。报告只读取服务端记录，不触发外呼或支付。</p><ol className="case-validation-steps"><li>导入脱敏案件，由另一位管理员复核</li><li>审批资产包策略，完成业务流程</li><li>核对回执与账簿，再与外部凭证比对</li></ol>{!connected?<div className="notice"><WarningCircle size={20}/><span>当前为演示模式。连接业务 API 后可核对实际导入的案件，演示样本不会生成真实验证结论。</span></div>:<form className="case-validation-form" onSubmit={inspect}><Field label="案件编号" hint="仅填写脱敏编号，无需姓名、手机号或身份证"><input required maxLength={40} value={caseId} onChange={e=>{sequence.current++;setBusy(false);setReport(null);setCaseId(e.target.value)}} placeholder="输入已导入的案件编号"/></Field><Button type="submit" variant="primary" disabled={busy||!caseId.trim()}>{busy?'正在核对':'核对案例证据'}</Button></form>}{error&&<p className="form-error" role="alert">{error}</p>}{report&&<div aria-live="polite"><div className="notice"><WarningCircle size={20}/><span>{report.status==='ready_for_external_review'?'服务端证据链具备外部复核条件':'证据尚不完整'}。来源真实性、实际服务商执行及银行凭证仍需业务方核实。</span></div><div className="case-validation-checks">{report.checks.map(check=><article key={check.id}>{check.passed?<CheckCircle size={20}/>:<WarningCircle size={20}/>}<div><b>{check.label}</b><small>{check.detail}</small></div><span>{check.passed?'已具备':'待处理'}</span></article>)}</div><KeyValue items={[["案件",report.case_id],["来源摘要",report.source_digest||'无独立复核导入来源'],["净回款（全部期间）",new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(report.confirmed_net_recovery_cents/100)],["账簿记录",report.ledger.length],["报告摘要",report.report_digest],["核对时间",new Date(report.generated_at).toLocaleString('zh-CN',{hour12:false})]]}/></div>}</section>
}
