import React,{useEffect,useMemo,useState} from 'react';
import {ArrowClockwise,Brain,CheckCircle,Clock,PhoneCall,ShieldCheck,Sparkle,UserCircleGear,WarningCircle} from '@phosphor-icons/react';
import {contactApi,membershipApi} from './api';
import {useApp} from './context';
import {Badge,Button,Empty,Field,Metrics,PageHead,Tabs} from './ui';

const nextWindow=()=>{const date=new Date(Date.now()+3600_000);return date.toISOString().slice(0,16)};

export function ControlCenter(){
 const a=useApp();
 const [tab,setTab]=useState('决策队列');
 const [state,setState]=useState({members:[],proposals:[],contacts:[],loading:false,error:''});
 const [memberForm,setMemberForm]=useState({target_user_id:'',requested_role:'operator',requested_status:'active',proposal_reason:'依据最小权限原则调整成员角色并进入独立复核。'});
 const [contactForm,setContactForm]=useState({case_id:'',activity_id:'',contact_reference:'CONTACT-REF-',scheduled_at:nextWindow()});
 const load=async()=>{if(a.backendStatus!=='connected')return;setState(s=>({...s,loading:true,error:''}));try{const [members,proposals,contacts]=await Promise.all([membershipApi.members(a.tenant),membershipApi.proposals(a.tenant),contactApi.list(a.tenant)]);setState({members,proposals,contacts,loading:false,error:''});setMemberForm(form=>({...form,target_user_id:form.target_user_id||members[0]?.user_id||''}));setContactForm(form=>({...form,case_id:form.case_id||a.visibleCases.find(row=>!row.blocked)?.case_id||'',contact_reference:form.contact_reference==='CONTACT-REF-'?`CONTACT-REF-${a.visibleCases.find(row=>!row.blocked)?.case_id||'CASE'}`:form.contact_reference}))}catch(error){setState(s=>({...s,loading:false,error:error.message}))}};
 useEffect(()=>{load()},[a.backendStatus,a.tenant]);
 const pending=state.proposals.filter(row=>row.status==='pending_review');
 const handoffs=state.contacts.filter(row=>row.status==='handoff');
 const activeContacts=state.contacts.filter(row=>['queued','initiated','ringing','answered'].includes(row.status));
 const queue=useMemo(()=>[
  ...pending.map(row=>({id:row.id,type:'成员权限',title:`${row.target_user_id} → ${row.requested_role}`,note:row.proposal_reason,owner:row.proposed_by,kind:'membership',row})),
  ...handoffs.map(row=>({id:row.id,type:'人工接管',title:`${row.case_id} · ${row.contact_reference}`,note:row.handoff_reason||'需要人工坐席继续处理',owner:row.handoff_requested_by,kind:'contact',row})),
 ],[state.proposals,state.contacts]);
 const proposeMember=async()=>{try{await membershipApi.propose(a.tenant,memberForm);a.notify('成员变更已进入独立复核');await load()}catch(error){a.notify(`提交失败：${error.message}`)}};
 const decide=async(row,decision)=>{try{await membershipApi.decide(a.tenant,row.id,{decision,expected_version:row.version,review_note:'已独立核验目标成员、最小权限和业务职责。'});a.notify(decision==='approve'?'成员权限变更已批准':'成员权限变更已驳回');await load()}catch(error){a.notify(`复核失败：${error.message}`)}};
 const createContact=async()=>{try{await contactApi.create(a.tenant,{...contactForm,activity_id:contactForm.activity_id||null,scheduled_at:new Date(contactForm.scheduled_at).toISOString()});a.notify('联系任务已通过确定性门禁并进入队列');await load()}catch(error){a.notify(`任务创建失败：${error.message}`)}};
 const handoff=async row=>{try{await contactApi.handoff(a.tenant,row.id,'对话出现复杂异议，需要人工坐席接管并保留证据。');a.notify('任务已转入人工接管');await load()}catch(error){a.notify(`接管失败：${error.message}`)}};
 if(a.backendStatus!=='connected')return <><PageHead title="AI 指挥台" description="把建议、审批、执行与证据集中在同一运营界面。"/><Empty title="需要连接业务 API" description="离线演示不生成虚构的成员审批或联系任务。"/></>;
 return <>
  <PageHead title="AI 指挥台" description="AI 汇总需要关注的事项，确定性规则和人员审批决定下一步。"><span className="ai-native-chip"><Sparkle size={15}/>Evidence-first</span><Button icon={ArrowClockwise} disabled={state.loading} onClick={load}>{state.loading?'同步中':'刷新状态'}</Button></PageHead>
  <section className="command-hero"><div className="command-orb"><Brain size={28}/></div><div><span className="eyebrow">OPERATING BRIEF</span><h2>{queue.length?`${queue.length} 项需要人工判断`:'当前没有待决策阻断项'}</h2><p>{queue.length?'AI 已按风险、时效与证据完整度整理队列；批准前不会执行高影响动作。':'运行中的任务继续受保护状态、联系时段、预算和渠道门禁约束。'}</p></div><div className="command-health"><span><i className="live-dot"/>服务端证据在线</span><small>租户隔离 · Maker–Checker · 全程审计</small></div></section>
  <Metrics items={[["待决策",queue.length,"需要人工判断"],["运行联系",activeContacts.length,"未包含真实拨号"],["人工接管",handoffs.length,"坐席责任明确"],["活跃成员",state.members.filter(row=>row.status==='active').length,"数据库授权"]]}/>
  {state.error&&<div className="form-error" role="alert">{state.error}</div>}
  <Tabs value={tab} onChange={setTab} items={[{id:'决策队列',label:'决策队列',count:queue.length},{id:'成员治理',label:'成员治理',count:pending.length},{id:'联系编排',label:'联系编排',count:activeContacts.length}]}/>
  {tab==='决策队列'&&<section className="decision-queue">{queue.map(item=><article key={`${item.kind}-${item.id}`}><span className={`decision-icon ${item.kind}`} >{item.kind==='membership'?<UserCircleGear size={20}/>:<PhoneCall size={20}/>}</span><div><span className="eyebrow">{item.type}</span><h3>{item.title}</h3><p>{item.note}</p><small>发起人 {item.owner} · 证据保存在服务端</small></div>{item.kind==='membership'&&<div className="decision-actions"><Button disabled={item.row.proposed_by===a.identity.actor_id} onClick={()=>decide(item.row,'reject')}>驳回</Button><Button variant="primary" disabled={item.row.proposed_by===a.identity.actor_id} onClick={()=>decide(item.row,'approve')}>独立批准</Button></div>}{item.kind==='contact'&&<Badge status="paused">等待坐席</Badge>}</article>)}{!queue.length&&<Empty title="队列已经清空" description="新的保护、审批或接管事项会按优先级进入这里。"/>}</section>}
  {tab==='成员治理'&&<div className="governance-layout"><section className="governance-panel"><div className="section-title"><h2>成员与最小权限</h2><ShieldCheck size={20}/></div><div className="member-list">{state.members.map(row=><article key={row.user_id}><span className="member-avatar">{row.display_name.slice(0,1)}</span><div><b>{row.display_name}</b><small>{row.user_id} · {row.email}</small></div><Badge status={row.status==='active'?'completed':'neutral'}>{row.role} · {row.status}</Badge></article>)}</div></section><section className="governance-panel"><div className="section-title"><h2>创建变更提案</h2><WarningCircle size={20}/></div><Field label="目标成员"><select value={memberForm.target_user_id} onChange={event=>setMemberForm({...memberForm,target_user_id:event.target.value})}>{state.members.map(row=><option key={row.user_id} value={row.user_id}>{row.display_name} · {row.role}</option>)}</select></Field><div className="field-grid"><Field label="目标角色"><select value={memberForm.requested_role} onChange={event=>setMemberForm({...memberForm,requested_role:event.target.value})}><option value="viewer">观察员</option><option value="operator">运营人员</option><option value="admin">管理员</option></select></Field><Field label="成员状态"><select value={memberForm.requested_status} onChange={event=>setMemberForm({...memberForm,requested_status:event.target.value})}><option value="active">启用</option><option value="inactive">停用</option></select></Field></div><Field label="调整依据"><textarea rows="4" value={memberForm.proposal_reason} onChange={event=>setMemberForm({...memberForm,proposal_reason:event.target.value})}/></Field><Button variant="primary" disabled={!memberForm.target_user_id||memberForm.proposal_reason.trim().length<8} onClick={proposeMember}>提交独立复核</Button></section></div>}
  {tab==='联系编排'&&<div className="governance-layout"><section className="governance-panel"><div className="section-title"><h2>受控联系任务</h2><PhoneCall size={20}/></div><div className="contact-list">{state.contacts.map(row=><article key={row.id}><span className="contact-state"><Clock size={18}/></span><div><b>{row.case_id} · {row.channel}</b><small>{row.contact_reference} · {new Date(row.scheduled_at).toLocaleString('zh-CN',{hour12:false})}</small></div><Badge status={row.status==='failed'?'blocked':row.status==='completed'?'completed':'running'}>{row.status}</Badge>{!['completed','failed','handoff','blocked'].includes(row.status)&&<Button onClick={()=>handoff(row)}>人工接管</Button>}</article>)}{!state.contacts.length&&<Empty title="暂无联系任务" description="任务通过时间、频次、保护与 Provider 就绪门禁后进入队列。"/>}</div></section><section className="governance-panel"><div className="section-title"><h2>创建联系计划</h2><CheckCircle size={20}/></div><Field label="案件"><select value={contactForm.case_id} onChange={event=>setContactForm({...contactForm,case_id:event.target.value,contact_reference:`CONTACT-REF-${event.target.value}`})}>{a.visibleCases.filter(row=>!row.blocked).map(row=><option key={row.case_id} value={row.case_id}>{row.case_id} · {row.status}</option>)}</select></Field><Field label="关联活动"><select value={contactForm.activity_id} onChange={event=>setContactForm({...contactForm,activity_id:event.target.value})}><option value="">不关联活动</option>{a.visibleActivities.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="脱敏联系引用"><input value={contactForm.contact_reference} onChange={event=>setContactForm({...contactForm,contact_reference:event.target.value})}/></Field><Field label="计划时间"><input type="datetime-local" value={contactForm.scheduled_at} onChange={event=>setContactForm({...contactForm,scheduled_at:event.target.value})}/></Field><div className="notice"><ShieldCheck size={18}/>创建任务不会直接拨号；执行前仍会检查保护、时段、频次与 Provider 状态。</div><Button variant="primary" disabled={!contactForm.case_id||contactForm.contact_reference.length<8} onClick={createContact}>提交受控任务</Button></section></div>}
 </>;
}
