import React,{useEffect,useRef,useState} from 'react';
import {Button,Empty} from './ui';
import {operationsApi,downloadCustomerMaterial} from './api';

const fields=[['case_id','案件编号列'],['payment_cents','付款金额列（分）'],['refund_cents','退款金额列（分）']];
const labels={matched:'金额一致 · 待外部核实',mismatch:'金额有差异',unavailable:'回执证据不完整',case_not_found:'案件未接入'};
function save(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvHeaders(text){const line=text.replace(/^\uFEFF/,'');let cell='',quoted=false,headers=[];for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(!quoted&&(c===','||c==='\n'||c==='\r')){headers.push(cell);cell='';if(c!==',')break}else cell+=c}if(!headers.length||cell)headers.push(cell);if(quoted||headers.length>30||headers.some(h=>!h||h.length>80)||new Set(headers).size!==headers.length)throw Error('CSV 表头无效，请使用 UTF-8 编码和唯一列名。');return headers}

export function CustomerMaterials({tenant,connected,identity}){
 const [file,setFile]=useState(null),[columns,setColumns]=useState([]),[mapping,setMapping]=useState({}),[reference,setReference]=useState(''),[ack,setAck]=useState(false),[items,setItems]=useState([]),[report,setReport]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const sequence=useRef(0),selection=useRef(0);const canWrite=connected&&['admin','operator'].includes(identity?.role);
 const load=async()=>{const id=++sequence.current;setError('');setReport(null);setItems([]);if(!connected)return;setBusy(true);try{const rows=await operationsApi.customerMaterials(tenant);if(id!==sequence.current)return;if(!Array.isArray(rows)||rows.some(r=>r.tenant_id!==tenant))throw Error('材料范围不匹配');setItems(rows)}catch(e){if(id===sequence.current)setError(e.message)}finally{if(id===sequence.current)setBusy(false)}};
 useEffect(()=>{setFile(null);setColumns([]);setMapping({});setReference('');setAck(false);selection.current++;load();return()=>{sequence.current++;selection.current++}},[tenant,connected]);
 const choose=async e=>{const id=++selection.current;setFile(null);setColumns([]);setMapping({});setAck(false);setReport(null);setError('');const next=e.target.files?.[0];if(!next)return;try{if(next.size<1||next.size>1000000)throw Error('请选择不超过 1 MB 的文件。');const kind=next.name.split('.').at(-1).toLowerCase();if(!['csv','pdf','png','jpg'].includes(kind))throw Error('支持 CSV、PDF、PNG 或 JPG 文件。');const headers=kind==='csv'?csvHeaders(await next.text()):[];if(id!==selection.current)return;setColumns(headers);setMapping(Object.fromEntries(fields.map(([f])=>[f,headers.includes(f)?f:''])));setFile(next)}catch(e){if(id===selection.current)setError(e.message)}};
 const run=async fn=>{const id=++sequence.current;setBusy(true);setReport(null);setError('');try{await fn(id)}catch(e){if(id===sequence.current)setError(e.message)}finally{if(id===sequence.current)setBusy(false)}};
 const readReport=(material)=>run(async id=>{const r=await operationsApi.customerMaterialReport(tenant,material.id);if(id!==sequence.current)return;if(r.tenant_id!==tenant||r.material?.id!==material.id||!Array.isArray(r.results))throw Error('材料核对范围不匹配');setReport(r)});
 return <section className="activity-section customer-materials" aria-label="客户材料接入"><div className="section-title"><h2>客户材料接入</h2><Button disabled={busy||!connected} onClick={load}>刷新材料</Button></div><p className="muted">上传脱敏材料，映射案件编号和金额。原文件加密留存，附件上传不等于验签或客户验收。</p>
 <ol className="material-steps"><li>选择材料</li><li>确认字段与来源</li><li>留存并核对</li></ol>
 <div className="material-toolbar"><Button onClick={()=>save(new Blob(['case_id,payment_cents,refund_cents\n'],{type:'text/csv;charset=utf-8'}),'customer-case-totals.csv')}>下载空白 CSV 模板</Button><span>每案一行 · 历史累计付款与退款 · 单位分</span></div>
 {!connected&&<p className="notice">可先查看字段映射；连接业务 API 后才能留存材料与核对。文件不会上传至演示站点。</p>}
 <form className="material-form" onSubmit={e=>{e.preventDefault();run(async id=>{const content=await file.arrayBuffer();if(id!==sequence.current)return;const bytes=new Uint8Array(content);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);const item=await operationsApi.createCustomerMaterial(tenant,{filename:file.name,source_reference:reference,file_kind:file.name.split('.').at(-1).toLowerCase(),content_base64:btoa(binary),mapping:file.name.toLowerCase().endsWith('.csv')?mapping:{},acknowledged:ack});if(id!==sequence.current)return;setItems(previous=>[item,...previous.filter(r=>r.id!==item.id)].slice(0,50));const r=await operationsApi.customerMaterialReport(tenant,item.id);if(id!==sequence.current)return;if(r.tenant_id!==tenant||r.material?.id!==item.id||!Array.isArray(r.results))throw Error('材料核对范围不匹配');setReport(r)})}}>
 <label className="field"><span>客户材料文件</span><input type="file" accept=".csv,.pdf,.png,.jpg" onChange={choose} disabled={busy}/><small>UTF-8 CSV 最多 50 个案件；文件不超过 1 MB。Excel 请先导出为 CSV。</small></label>
 <label className="field"><span>来源记录编号</span><input required pattern="[A-Za-z0-9][A-Za-z0-9._/-]{3,159}" maxLength={160} placeholder="BANK/2026-001" value={reference} onChange={e=>{setReference(e.target.value);setReport(null)}} disabled={busy}/></label>
 {columns.length>0&&<div className="material-mapping">{fields.map(([f,label])=><label className="field" key={f}><span>{label}</span><select required value={mapping[f]||''} disabled={busy} onChange={e=>{setMapping({...mapping,[f]:e.target.value});setReport(null)}}><option value="">请选择列</option>{columns.map(c=><option key={c} value={c}>{c}</option>)}</select></label>)}</div>}
 {file&&!columns.length&&<p className="muted">此附件仅加密留存，内容识别与真实性核验待人工完成。</p>}
 <label className="check-agreement"><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/><span>确认材料已获授权并完成脱敏；金额为每个案件的历史累计汇总。</span></label>
 <Button variant="primary" disabled={!canWrite||!file||!ack||busy}>{busy?'正在处理':'留存材料并核对'}</Button>{connected&&!canWrite&&<span className="muted">需要运营人员或管理员权限。</span>}
 </form>{error&&<p className="form-error" role="alert">{error}</p>}
 {report&&<div className="material-report"><div className="section-title"><h3>材料核对结果</h3><Button onClick={()=>save(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'customer-material-report.json')}>下载材料核对报告</Button></div><p className="muted">{report.status==='attachment_only'?'附件已留存，待人工核验。':'按每个案件全部历史账簿核对付款与退款；金额一致仍需外部核实。'}</p><div className="table-scroll"><table><thead><tr><th>案件</th><th>结果</th><th>付款差额（分）</th><th>退款差额（分）</th></tr></thead><tbody>{report.results.map(r=><tr key={r.case_id}><td>{r.case_id}</td><td>{labels[r.status]||'待确认'}</td><td>{r.payment_difference_cents??'不可比对'}</td><td>{r.refund_difference_cents??'不可比对'}</td></tr>)}</tbody></table></div><details><summary>来源与证据摘要</summary><p>{report.material.source_reference}</p><code>{report.material.source_digest}</code></details></div>}
 <h3>已留存材料</h3>{items.length?<div className="material-list">{items.map(item=><article key={item.id}><div><b>{item.filename}</b><p>{item.source_reference} · {item.case_count} 个案件</p></div><div><Button disabled={busy} onClick={()=>readReport(item)}>重新核对</Button>{canWrite&&<Button disabled={busy} onClick={()=>run(async id=>{const blob=await downloadCustomerMaterial(tenant,item.id);if(id===sequence.current)save(blob,`${item.id}.${item.file_kind}`)})}>下载原件</Button>}</div></article>)}</div>:<Empty title={busy?'正在读取材料':'暂无已留存材料'} description="材料只保存在所选工作空间，失败不会转为本地保存。"/>}
 </section>
}
