import React,{useEffect,useRef,useState} from 'react';
import {operationsApi} from './api';
import {Button,Empty} from './ui';
const initial={name:'',endpoint:'',credential:'',case_id:'case_id',payment_cents:'payment_cents',refund_cents:'refund_cents',interval_minutes:60};
export function CustomerConnectors({tenant,connected,identity}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(initial),[edit,setEdit]=useState(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const seq=useRef(0);const admin=connected&&identity?.role==='admin';
 const load=async()=>{const id=++seq.current;setRows([]);setError('');if(!connected)return;setBusy(true);try{const r=await operationsApi.customerConnectors(tenant);if(id!==seq.current)return;if(!Array.isArray(r)||r.some(v=>v.tenant_id!==tenant))throw Error('连接器范围不匹配');setRows(r)}catch(e){if(id===seq.current)setError(e.message)}finally{if(id===seq.current)setBusy(false)}};
 useEffect(()=>{setForm(initial);setEdit(null);setAck(false);load();return()=>{seq.current++}},[tenant,connected]);
 const act=async fn=>{const id=++seq.current;setBusy(true);setError('');try{await fn();if(id!==seq.current)return;setForm(initial);setEdit(null);setAck(false);await load()}catch(e){if(id===seq.current){setError(e.message);setForm(v=>({...v,credential:''}));setBusy(false)}}};
 const field=(key,label,type='text')=><label className="field"><span>{label}</span><input type={type} required={key!=='credential'||!edit} value={form[key]} disabled={!admin||busy} min={type==='number'?5:undefined} max={type==='number'?1440:undefined} autoComplete={key==='credential'?'new-password':'off'} onChange={e=>{setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value});setAck(false)}}/></label>;
 return <section className="activity-section" aria-label="客户业务连接器"><div className="section-title"><h2>客户业务连接器</h2><Button disabled={!connected||busy} onClick={load}>刷新连接器</Button></div><p className="muted">从已授权客户系统拉取案件金额汇总。先保存、连接测试，再启用；修改配置会停止自动同步并使旧测试失效。</p><form className="material-form" onSubmit={e=>{e.preventDefault();act(()=>operationsApi.saveCustomerConnector(tenant,edit?.id,{name:form.name,endpoint:form.endpoint,credential:form.credential||null,mapping:{case_id:form.case_id,payment_cents:form.payment_cents,refund_cents:form.refund_cents},interval_minutes:form.interval_minutes,expected_version:edit?.version||0,acknowledged:ack}))}}>{field('name','连接器名称')}{field('endpoint','客户 HTTPS 接口','url')}{field('credential',edit?'新 API 凭证（留空保留）':'API 凭证','password')}{field('interval_minutes','同步间隔（分钟）','number')}{field('case_id','案件编号字段')}{field('payment_cents','付款金额分字段')}{field('refund_cents','退款金额分字段')}<label className="check-agreement"><input type="checkbox" checked={ack} disabled={!admin||busy} onChange={e=>setAck(e.target.checked)}/><span>客户已授权此数据源，拉取内容已脱敏，允许按当前间隔同步。</span></label><div className="material-toolbar"><Button type="submit" variant="primary" disabled={!admin||busy||!ack}>{edit?'更新连接器':'保存连接器'}</Button>{edit&&<Button onClick={()=>{setForm(initial);setEdit(null);setAck(false)}}>取消编辑</Button>}</div></form>{error&&<p role="alert" className="form-error">{error}</p>}{rows.length?<div className="material-list">{rows.map(r=><article key={r.id}><div><b>{r.name} · v{r.version}</b><p>{r.enabled?'已启用':'未启用'} · {r.test_current?'当前配置测试通过':'需要连接测试'} · 每 {r.interval_minutes} 分钟</p><p className="connector-endpoint">{r.endpoint}</p>{r.job&&<p>同步：{({queued:'等待处理',running:'处理中',failed:'失败',succeeded:'本页已接入',cancelled:'已取消'})[r.job.status]||r.job.status} · {r.job.result?.events_accepted??0} 个已接入事件</p>}{r.job?.error&&<p>{r.job.error}</p>}</div><div className="connector-actions"><Button disabled={!admin||busy} onClick={()=>{setEdit(r);setAck(false);setForm({...initial,name:r.name,endpoint:r.endpoint,...r.mapping,interval_minutes:r.interval_minutes})}}>编辑配置</Button><Button disabled={!admin||busy} onClick={()=>act(()=>operationsApi.customerConnectorAction(tenant,r.id,'test',{expected_version:r.version,acknowledged:true}))}>连接测试</Button><Button disabled={!admin||busy||(!r.enabled&&!r.test_current)} onClick={()=>act(()=>operationsApi.customerConnectorAction(tenant,r.id,'enable',{expected_version:r.version,acknowledged:true,enabled:!r.enabled}))}>{r.enabled?'停止同步':'启用同步'}</Button><Button disabled={!admin||busy||!r.enabled||!r.test_current} onClick={()=>act(()=>operationsApi.customerConnectorAction(tenant,r.id,'sync'))}>立即同步</Button>{r.job?.status==='failed'&&r.job.attempt<r.job.max_attempts&&<Button disabled={!admin||busy} onClick={()=>act(()=>operationsApi.retryCustomerSync(tenant,r.job.id))}>重试失败页</Button>}</div></article>)}</div>:<Empty title={connected?'暂无客户连接器':'连接业务 API 后配置数据源'} description="没有客户凭证时不会生成成功测试或同步记录。"/>}</section>
}
