const TOKEN_KEY='repayguard.auth.tokens';
const LEGACY_ACCESS_KEY='luheng.auth.token';
const FLOW_KEY='repayguard.auth.pkce';

const config=()=>({authority:import.meta.env?.VITE_OIDC_AUTHORITY||'',clientId:import.meta.env?.VITE_OIDC_CLIENT_ID||'',redirectUri:import.meta.env?.VITE_OIDC_REDIRECT_URI||(typeof location!=='undefined'?`${location.origin}${location.pathname}`:''),scope:import.meta.env?.VITE_OIDC_SCOPE||'openid profile email offline_access',audience:import.meta.env?.VITE_OIDC_AUDIENCE||'',logoutUri:import.meta.env?.VITE_OIDC_LOGOUT_URI||''});
const encode=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const random=()=>encode(crypto.getRandomValues(new Uint8Array(32)));
const challenge=async verifier=>encode(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));
const endpoints=()=>{const c=config();const base=c.authority.replace(/\/$/,'');return {...c,authorize:`${base}/authorize`,token:`${base}/oauth/token`,logout:c.logoutUri||`${base}/v2/logout`}};
const browserStorage=()=>typeof localStorage==='undefined'?null:localStorage;
const flowStorage=()=>typeof sessionStorage==='undefined'?null:sessionStorage;
const loadTokens=()=>{try{return JSON.parse(browserStorage()?.getItem(TOKEN_KEY)||'null')}catch{return null}};
const saveTokens=payload=>{const tokens={access_token:payload.access_token,refresh_token:payload.refresh_token||null,id_token:payload.id_token||null,expires_at:Date.now()+Math.max(30,Number(payload.expires_in||300))*1000};browserStorage()?.setItem(TOKEN_KEY,JSON.stringify(tokens));browserStorage()?.setItem(LEGACY_ACCESS_KEY,tokens.access_token);return tokens};

export const oidcConfigured=()=>{const c=config();return Boolean(c.authority&&c.clientId&&c.redirectUri)};
export async function beginOidcLogin(){if(!oidcConfigured())throw new Error('浏览器 OIDC 参数尚未配置');const c=endpoints();const verifier=random();const state=random();const nonce=random();flowStorage()?.setItem(FLOW_KEY,JSON.stringify({verifier,state,nonce,createdAt:Date.now()}));const params=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:c.redirectUri,scope:c.scope,state,nonce,code_challenge:await challenge(verifier),code_challenge_method:'S256'});if(c.audience)params.set('audience',c.audience);location.assign(`${c.authorize}?${params}`)}
export async function completeOidcCallback(){const query=new URLSearchParams(location.search);const code=query.get('code');const state=query.get('state');if(!code)return false;const flow=JSON.parse(flowStorage()?.getItem(FLOW_KEY)||'null');if(!flow||flow.state!==state||Date.now()-flow.createdAt>10*60*1000)throw new Error('登录回调状态无效或已经过期');const c=endpoints();const body=new URLSearchParams({grant_type:'authorization_code',client_id:c.clientId,code,redirect_uri:c.redirectUri,code_verifier:flow.verifier});const response=await fetch(c.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error(`OIDC 授权码交换失败（${response.status}）`);saveTokens(await response.json());flowStorage()?.removeItem(FLOW_KEY);history.replaceState({},'',`${location.pathname}${location.hash||''}`);return true}
export async function ensureFreshAccessToken(){const tokens=loadTokens();if(!tokens)return browserStorage()?.getItem(LEGACY_ACCESS_KEY)||'';if(tokens.expires_at>Date.now()+60000)return tokens.access_token;if(!tokens.refresh_token||!oidcConfigured())return tokens.access_token||'';const c=endpoints();const body=new URLSearchParams({grant_type:'refresh_token',client_id:c.clientId,refresh_token:tokens.refresh_token});const response=await fetch(c.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok){clearOidcSession();return ''}const refreshed=await response.json();return saveTokens({...refreshed,refresh_token:refreshed.refresh_token||tokens.refresh_token}).access_token}
export function clearOidcSession(){browserStorage()?.removeItem(TOKEN_KEY);browserStorage()?.removeItem(LEGACY_ACCESS_KEY);flowStorage()?.removeItem(FLOW_KEY)}
export function logoutOidc(){const c=endpoints();const tokens=loadTokens();clearOidcSession();if(!oidcConfigured()){location.reload();return}const params=new URLSearchParams({client_id:c.clientId,returnTo:location.origin});if(tokens?.id_token)params.set('id_token_hint',tokens.id_token);location.assign(`${c.logout}?${params}`)}
