import React,{useEffect,useState} from 'react';
import {CheckCircle,WarningCircle,ArrowClockwise} from '@phosphor-icons/react';
import {useApp} from './context';
import {operationsApi} from './api';
import {Button,Empty,Metrics,PageHead} from './ui';
import {ConnectionReadiness} from './connection-readiness';
import {CaseValidation} from './case-validation';
import {PilotEvidence} from './pilot-evidence';

const money=cents=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format((cents||0)/100);

export function PilotAcceptance(){
 const a=useApp();
 const [state,setState]=useState({loading:false,error:'',scorecard:null,metrics:null,providers:null,gate:null,preflight:null});
 const load=async()=>{if(a.backendStatus!=='connected')return;setState(s=>({...s,loading:true,error:''}));try{const [scorecard,metrics,providers,gate,preflight]=await Promise.all([operationsApi.pilotScorecard(a.tenant),operationsApi.metrics(a.tenant),operationsApi.providerScorecard(a.tenant),operationsApi.releaseGate(a.tenant),operationsApi.pilotPreflight(a.tenant)]);setState({loading:false,error:'',scorecard,metrics,providers,gate,preflight})}catch(error){setState({loading:false,error:error.message,scorecard:null,metrics:null,providers:null,gate:null,preflight:null})}};
 useEffect(()=>{load()},[a.backendStatus,a.tenant]);
 if(a.backendStatus!=='connected')return <><PageHead title="试点验收" description="使用服务端权威数据判定试点是否可进入下一阶段。"/><ConnectionReadiness tenant={a.tenant} connected={a.backendStatus==='connected'}/><CaseValidation tenant={a.tenant} connected={false}/><Empty title="需要连接业务 API" description="Sites 和离线演示不会生成虚构的试点验收结论。"/></>;
 const s=state.scorecard,m=state.metrics,p=state.providers,g=state.gate,pf=state.preflight;
 return <><PageHead title="试点验收" description="权威目录、不可变账簿、生产配置与运行指标的联合门禁。"><Button icon={ArrowClockwise} disabled={state.loading} onClick={load}>{state.loading?'正在刷新':'刷新证据'}</Button></PageHead><ConnectionReadiness tenant={a.tenant} connected={a.backendStatus==='connected'}/><CaseValidation tenant={a.tenant} connected={true}/>{state.error&&<div className="form-error" role="alert">{state.error}</div>}{s&&<><section className={`notice ${s.status==='ready'?'success':''}`}>{s.status==='ready'?<CheckCircle size={20}/>:<WarningCircle size={20}/>}<b>{s.status==='ready'?'业务验收门禁已就绪':'还有业务事项需处理'}</b><span>证据生成于 {new Date(s.generated_at).toLocaleString('zh-CN',{hour12:false})}</span></section><Metrics items={[["在管案件",s.portfolio.case_count,`${s.portfolio.protected_case_count} 个保护暂停`],["确认净回款",money(s.money.confirmed_net_recovery_cents),"不可变账簿"],["生产门禁",`${g?.automated?.passed||0}/${g?.automated?.total||0}`,g?.status==='ready_for_manual_acceptance'?'待人工验收':'自动检查未通过'],["支付异常",p?.payment_exceptions?.count||0,money(p?.payment_exceptions?.amount_cents||0)]]}/>{g&&<section className="release-gate"><div className="section-title"><h2>生产发布门禁</h2><span>{g.automated.passed}/{g.automated.total} 自动检查通过</span></div><div>{g.automated.checks.map(item=><article key={item.id}>{item.status?<CheckCircle size={18}/>:<WarningCircle size={18}/>}<span><b>{item.label}</b><small>{item.detail}</small></span></article>)}</div></section>}{pf&&<section className="release-gate"><div className="section-title"><h2>后端试点预检</h2><span>{pf.status==='ready'?'已就绪':'尚未就绪'}</span></div><div>{pf.checks.map(item=><article key={item.id}>{item.passed?<CheckCircle size={18}/>:<WarningCircle size={18}/>}<span><b>{{migrations:'数据库迁移', 'worker-heartbeat':'Worker 心跳与租约','independent-admins':'独立管理员','tenant-active':'租户激活',acceptance:'联合验收'}[item.id]}</b><small>{item.passed?'通过':'待处理'}</small></span></article>)}</div></section>}<PilotEvidence tenant={a.tenant} identity={a.identity} gate={g} onRefresh={load}/><div className="workspace-grid"><section className="activity-section"><h2>业务阻断项</h2>{s.blockers.length?<ul className="guide">{s.blockers.map(item=><li key={item}>{item}</li>)}</ul>:<p className="notice success">无服务端阻断项。</p>}</section><section className="event-feed"><h2>运行健康</h2><dl className="kv"><div><dt>请求总数</dt><dd>{m?.requests_total||0}</dd></div><div><dt>p50</dt><dd>{m?.latency_ms?.p50||0} ms</dd></div><div><dt>p95</dt><dd>{m?.latency_ms?.p95||0} ms</dd></div><div><dt>指标样本</dt><dd>{m?.sample_size||0}</dd></div></dl></section></div></>}</>;
}
