import React,{useEffect,useRef,useState} from 'react';
export {AgentScreen,Logs,Strategy,Usage,Settings} from './operations';
export {Integrations} from './integrations';
import {Plus,CalendarBlank,ArrowRight,ArrowUpRight,ArrowLeft,ArrowsDownUp,Rows,Pause,Play,Robot,ShieldCheck,Clock,CheckCircle,Circle,FolderSimple,Files,Database,DownloadSimple,UploadSimple,Lightning,BookOpen,Receipt,WarningCircle,GearSix,Buildings,ChartBar,CaretLeft,CaretRight,FunnelSimple,TrendUp,PhoneCall,Handshake,MagicWand,CurrencyCircleDollar,DotsThree,Eye,Sparkle} from '@phosphor-icons/react';
import {useApp} from './context';
import {Button,IconButton,Badge,PageHead,Tabs,Search,Metrics,Empty,KeyValue,EventFeed,Field} from './ui';
import {money,reasonText,downloadCSV} from './model';

const sum=(rows,key)=>Math.round(rows.reduce((s,r)=>s+(Number(r[key])||0),0)*100)/100;
function Scope({value,onChange}){const a=useApp();return <select aria-label="筛选资产包" value={value} onChange={e=>onChange(e.target.value)}><option value="all">全部资产包</option>{a.visiblePackages.map(p=><option value={p.package_id} key={p.package_id}>{p.package_id} · {p.title}</option>)}</select>}
function WorkspaceMetrics({scope='all'}){const a=useApp();const l=a.visibleLedger.filter(x=>scope==='all'||x.package_id===scope);const c=a.visibleCases.filter(x=>scope==='all'||x.package_id===scope);const collected=scope==='all'&&a.financialOverview.summary?a.financialOverview.summary.collected_commission_cents/100:0;return <Metrics items={[["在管案件",c.length,"样本案件"],["确认净回款",money(sum(l,'cash_yuan')),"已到账，已扣除退款"],["应计佣金",money(sum(l,'commission_yuan')),"按委托规则计提"],["实际收佣",money(collected),collected?"来自佣金实收账簿":"尚未收到佣金结算"]]}/>}
export function Activities(){const a=useApp();const [tab,setTab]=useState('all');const [q,setQ]=useState('');const [selected,setSelected]=useState([]);const [sort,setSort]=useState(false);const [dense,setDense]=useState(false);const [page,setPage]=useState(1);
 const scoped=a.visibleActivities.filter(x=>a.scope==='all'||x.package===a.scope);
 const filtered=scoped.filter(x=>(tab==='all'||(tab==='paused'?['paused','blocked'].includes(x.status):x.status===tab))&&(x.name+x.caseIds.join('')+x.id).toLowerCase().includes(q.toLowerCase()));
 const rows=(sort?[...filtered].sort((x,y)=>x.name.localeCompare(y.name,'zh-CN')):filtered).slice((page-1)*5,page*5);
 const select=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <><PageHead title="清收活动" description="让 AI 持续执行，按实际回款衡量结果。"><span className="date-label"><CalendarBlank size={17}/>累计至 2026.09.12</span><Button icon={Plus} variant="primary" onClick={()=>a.setDialog({type:'create'})}>创建活动</Button></PageHead><WorkspaceMetrics scope={a.scope}/>
 <div className="workspace-grid"><section className="activity-section"><Tabs value={tab} onChange={v=>{setTab(v);setPage(1);setSelected([])}} items={[{id:'all',label:'全部活动',count:scoped.length},{id:'running',label:'运行中',count:scoped.filter(x=>x.status==='running').length},{id:'completed',label:'已完成',count:scoped.filter(x=>x.status==='completed').length},{id:'paused',label:'已暂停',count:scoped.filter(x=>['paused','blocked'].includes(x.status)).length}]}/>
 <div className="table-toolbar"><Scope value={a.scope} onChange={s=>{a.setScope(s);setPage(1);setSelected([])}}/><Search value={q} onChange={v=>{setQ(v);setPage(1)}} placeholder="搜索活动、案件编号…"/><IconButton icon={ArrowsDownUp} label={sort?'恢复默认排序':'按活动名称排序'} onClick={()=>setSort(!sort)}/><IconButton icon={Rows} label={dense?'切换宽松行高':'切换紧凑行高'} onClick={()=>setDense(!dense)}/></div>
 {selected.length>0&&<div className="bulk-bar"><b>已选 {selected.length} 项</b><button onClick={()=>{a.setActivityStatus(selected,'paused');setSelected([])}}><Pause size={15}/>暂停</button><button onClick={()=>{a.setActivityStatus(selected,'running');setSelected([])}}><Play size={15}/>恢复</button><button onClick={()=>setSelected([])}>取消选择</button></div>}
 <div className="table-scroll"><table className={dense?'data-table dense activity-table':'data-table activity-table'}><thead><tr><th className="check-col"><input type="checkbox" aria-label="选择当前页全部活动" checked={rows.length>0&&rows.every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?rows.map(x=>x.id):[])}/></th><th>活动 / 目标</th><th>范围</th><th>状态</th><th>AI 下一步</th><th>预算</th><th className="time-col">更新</th><th/></tr></thead><tbody>{rows.map((x,i)=><tr key={x.id} className={selected.includes(x.id)?'selected':i===0&&!q&&tab==='all'?'featured':''}><td><input type="checkbox" aria-label={`选择${x.name}`} checked={selected.includes(x.id)} onChange={()=>select(x.id)}/></td><td><button className="cell-title" onClick={()=>a.navigate('agents/'+x.id)}>{x.name}</button><small>{x.goal}</small></td><td>{x.package}<small>{x.caseIds.length} 个案件 · {x.mode==='channel'?'授权渠道':'模拟运行'}</small></td><td><Badge status={x.status}/></td><td><span className="next-text">{x.next}</span><small>{x.status==='blocked'?'触达已自动停止':x.status==='completed'?'结果与依据已留存':'受策略和门禁约束'}</small></td><td className="number">{money(x.budget*x.caseIds.length)}<small>上限</small></td><td className="time-col muted">{x.updated}</td><td><IconButton icon={ArrowUpRight} label={`打开${x.name}`} onClick={()=>a.navigate('agents/'+x.id)}/></td></tr>)}</tbody></table></div>
 {!rows.length&&<Empty action={<Button onClick={()=>{setQ('');setTab('all');a.setScope('all');setPage(1)}}>清空筛选</Button>}/>}
 <div className="table-footer"><span>共 {filtered.length} 个活动</span><div><IconButton icon={CaretLeft} label="上一页" disabled={page===1} onClick={()=>setPage(page-1)}/><span className="page-number">{page}</span><IconButton icon={CaretRight} label="下一页" disabled={page*5>=filtered.length} onClick={()=>setPage(page+1)}/></div></div></section><EventFeed compact/></div>
 <div className="workspace-footer"><h3>本工作空间</h3><div><button onClick={()=>a.navigate('assets')}><FolderSimple size={24}/><span><b>{a.visiblePackages.length} 个资产包</b><small>按委托范围独立管理</small></span></button><button onClick={()=>a.navigate('cases')}><Files size={24}/><span><b>{a.visibleCases.length} 个案件</b><small>查看案件与履约状态</small></span></button><button onClick={()=>a.navigate('payments')}><Database size={24}/><span><b>佣金模式</b><small>按实际回款计提</small></span></button><button className="text-link" onClick={()=>a.navigate('settings')}>管理工作空间 <ArrowRight size={16}/></button></div></div></>;
}
const overviewRanges={
 week:{label:'近 7 天',recovery:[38,52,45,68,61,76,88],commission:[25,34,31,49,45,58,67]},
 month:{label:'近 30 天',recovery:[42,61,55,78,66,83,72,91,74,86,95,88],commission:[24,38,31,48,43,56,49,65,55,63,71,67]},
 quarter:{label:'近 90 天',recovery:[28,39,51,45,62,58,73,68,81,76,92,88],commission:[21,28,35,31,42,40,51,48,58,55,66,63]}
};
const heatCells=Array.from({length:294},(_,i)=>((i*17+i*i*3)%11));
function canvasColors(){const css=getComputedStyle(document.documentElement);return {border:css.getPropertyValue('--border').trim(),muted:css.getPropertyValue('--muted').trim(),surface:css.getPropertyValue('--chart-track').trim()||'#e7e7e8',lime:css.getPropertyValue('--chart-lime').trim()||'#82e600',purple:css.getPropertyValue('--chart-purple').trim()||'#7c3aed'}}
function useCanvas(draw,deps){const ref=useRef(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const render=()=>{const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(rect.width*dpr));canvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);draw(ctx,rect.width,rect.height,canvasColors())};render();const observer=new ResizeObserver(render);observer.observe(canvas);return()=>observer.disconnect()},deps);return ref}
function RecoveryBarChart({values,range,theme}){const labels=range==='week'?['一','二','三','四','五','六','日']:values.map((_,i)=>String(i+1));const ref=useCanvas((ctx,w,h,color)=>{const pad={l:38,r:4,t:5,b:23};const plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b;ctx.font="10px Inter, 'Noto Sans SC', sans-serif";ctx.textBaseline='middle';ctx.fillStyle=color.muted;ctx.textAlign='left';[['¥10K',0],['¥5K',.5],['¥0',1]].forEach(([label,r])=>{const y=pad.t+plotH*r;ctx.strokeStyle=color.border;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.l,y+.5);ctx.lineTo(w-pad.r,y+.5);ctx.stroke();ctx.fillText(label,0,y)});const slot=plotW/values.length;const bw=Math.min(34,slot*.54);values.forEach((value,i)=>{const x=pad.l+slot*i+(slot-bw)/2;ctx.fillStyle=color.surface;ctx.beginPath();ctx.roundRect(x,pad.t,bw,plotH,Math.min(11,bw/2));ctx.fill();const fillH=Math.max(8,plotH*value/100);ctx.fillStyle=color.lime;ctx.beginPath();ctx.roundRect(x,pad.t+plotH-fillH,bw,fillH,Math.min(11,bw/2));ctx.fill();ctx.fillStyle=color.muted;ctx.textAlign='center';ctx.fillText(labels[i],x+bw/2,h-7)});},[values,range,theme]);return <canvas className="recovery-bar-canvas" ref={ref} role="img" aria-label={`${range==='week'?'近 7 天':range==='month'?'近 30 天':'近 90 天'}确认净回款趋势`}/>}
function MiniLineChart({values,theme}){const ref=useCanvas((ctx,w,h,color)=>{const pad={l:36,r:4,t:6,b:18};const plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b;const max=Math.max(...values)*1.08;const pts=values.map((v,i)=>[pad.l+i*plotW/(values.length-1),pad.t+plotH-(v/max)*plotH]);ctx.font="9px Inter, 'Noto Sans SC', sans-serif";ctx.textBaseline='middle';[['¥3K',.12],['¥2K',.5],['¥1K',.88]].forEach(([label,r])=>{const y=pad.t+plotH*r;ctx.strokeStyle=color.border;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.l,y+.5);ctx.lineTo(w-pad.r,y+.5);ctx.stroke();ctx.fillStyle=color.muted;ctx.textAlign='left';ctx.fillText(label,0,y)});ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.lineTo(pts.at(-1)[0],pad.t+plotH);ctx.lineTo(pts[0][0],pad.t+plotH);ctx.closePath();ctx.fillStyle='rgba(117, 223, 0, 0.12)';ctx.fill();ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.strokeStyle='#65bd00';ctx.lineWidth=2;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();['1周','2周','3周','4周'].forEach((label,i)=>{ctx.fillStyle=color.muted;ctx.textAlign=i===0?'left':i===3?'right':'center';ctx.fillText(label,pad.l+i*plotW/3,h-5)})},[values,theme]);return <canvas className="mini-line-chart" ref={ref} role="img" aria-label="应计佣金趋势曲线"/>}
function HeatmapChart({values,theme}){const ref=useCanvas((ctx,w,h,color)=>{const rows=7,cols=Math.ceil(values.length/rows),gap=3;const cell=Math.max(4,Math.min(8,(w-(cols-1)*gap)/cols));const chartW=cols*cell+(cols-1)*gap;const offsetX=Math.max(0,(w-chartW)/2);const palette=[color.border,'#ddd0ff','#b99bff','#8b5cf6',color.purple];values.forEach((v,i)=>{const col=Math.floor(i/rows),row=i%rows;ctx.fillStyle=palette[Math.min(4,Math.floor(v/2))];ctx.beginPath();ctx.roundRect(offsetX+col*(cell+gap),row*(cell+gap),cell,cell,2);ctx.fill()})},[values,theme]);return <canvas className="activity-heatmap" ref={ref} role="img" aria-label="过去十三周 AI 自动执行活跃度"/>}
export function Overview(){const a=useApp();const [range,setRange]=useState('month');const [q,setQ]=useState('');const [status,setStatus]=useState('all');const [filtersOpen,setFiltersOpen]=useState(false);const [selected,setSelected]=useState([]);const chart=overviewRanges[range];const ledgerCash=sum(a.visibleLedger,'cash_yuan');const ledgerCommission=sum(a.visibleLedger,'commission_yuan');const running=a.visibleActivities.filter(x=>x.status==='running');const blocked=a.visibleCases.filter(c=>c.blocked);const rows=a.visibleCases.filter(c=>(status==='all'||(status==='blocked'?c.blocked:c.status===status))&&(c.case_id+c.package_id+c.status+(c.reason||'')).toLowerCase().includes(q.toLowerCase())).slice(0,8);const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const selectAll=()=>setSelected(s=>rows.length&&rows.every(r=>s.includes(r.case_id))?s.filter(id=>!rows.some(r=>r.case_id===id)):[...new Set([...s,...rows.map(r=>r.case_id)])]);return <div className="overview-dashboard">
 <PageHead title="晚上好，Terry" description="AI 清收经营与执行状态，一屏掌握。"><span className="sync-label"><span className="live-dot"/>10:48 已同步</span><Button icon={FunnelSimple} className={filtersOpen?'is-active':''} onClick={()=>setFiltersOpen(!filtersOpen)}>筛选</Button><Button icon={Plus} variant="primary" onClick={()=>a.setDialog({type:'create'})}>创建活动</Button></PageHead>
 {filtersOpen&&<div className="overview-filter-panel"><span>经营范围</span><Scope value={a.scope} onChange={a.setScope}/><span>统计周期</span><select value={range} onChange={e=>setRange(e.target.value)}><option value="week">近 7 天</option><option value="month">近 30 天</option><option value="quarter">近 90 天</option></select><button className="text-link" onClick={()=>{a.setScope('all');setRange('month')}}>重置筛选</button></div>}
 <section className="overview-exception-strip"><span><WarningCircle size={19}/><b>{blocked.length} 个案件已保护暂停</b><small>3 个临近 SLA · 新触达已阻断</small></span><button className="text-link" onClick={()=>a.navigate('exceptions')}>进入异常中心 <ArrowRight size={14}/></button></section>
 <div className="overview-grid overview-grid-top">
  <section className="dashboard-card ai-now-card"><div className="card-head"><div><span className="card-kicker">AI 任务</span><strong>{a.visibleActivities.length}</strong><small>{running.length} 运行 · {a.visibleActivities.filter(x=>['paused','blocked'].includes(x.status)).length} 暂停</small></div><button className="text-link" onClick={()=>a.navigate('agents')}>查看全部 <ArrowRight size={14}/></button></div><div className="agent-brief-list">{a.visibleActivities.slice(0,4).map((x,i)=><button key={x.id} className="agent-brief" onClick={()=>a.navigate('agents/'+x.id)}><span className={`agent-brief-icon tone-${i%3+1}`}><Robot size={18}/></span><span><b>{x.name}</b><small>{x.package}</small></span><Badge status={x.status}/></button>)}</div><button className="ai-insight" onClick={()=>a.setCopilotOpen(true)}><Sparkle size={16} weight="fill"/><span><b>询问履衡 AI</b><small>查询指标、案件或下达任务目标</small></span><ArrowRight size={14}/></button><div className="ai-card-footer"><span><span className="live-dot"/>核心服务正常 · {blocked.length} 个保护中</span><button onClick={()=>a.navigate('logs')}>执行动态 <ArrowUpRight size={14}/></button></div></section>
  <section className="dashboard-card recovery-chart-card"><div className="card-head"><div><span className="card-kicker">确认净回款</span><div className="metric-value-row"><strong>{money(ledgerCash)}</strong><span className="positive-pill"><TrendUp size={13}/> 14.8%</span></div><small>已到账并扣除退款 · {chart.label}</small></div><div className="segmented">{[['week','周'],['month','月'],['quarter','季']].map(([id,label])=><button key={id} className={range===id?'active':''} onClick={()=>setRange(id)}>{label}</button>)}</div></div><RecoveryBarChart values={chart.recovery} range={range} theme={a.theme}/></section>
 </div>
 <div className="overview-grid overview-grid-middle">
  <section className="dashboard-card commission-card"><div className="card-head"><div><span className="card-kicker">应计佣金</span><div className="metric-value-row"><strong>{money(ledgerCommission)}</strong><span className="positive-pill">+9.4%</span></div><small>按委托规则计提，不等于实收</small></div><button className="icon-btn" aria-label="查看回款与佣金" onClick={()=>a.navigate('payments')}><ArrowUpRight size={18}/></button></div><MiniLineChart values={chart.commission} theme={a.theme}/><div className="commission-legend"><span><i className="legend-dot confirmed"/>应计佣金</span><button className="text-link" onClick={()=>a.navigate('payments')}>查看对账 <ArrowRight size={14}/></button></div></section>
  <section className="dashboard-card automation-card"><div className="card-head"><div><span className="card-kicker">AI 自动化质量</span><div className="metric-value-row"><strong>92.4%</strong><span className="positive-pill">+3.2%</span></div><small>常规案件无需人工介入</small></div><div className="segmented compact"><button className="active">周</button><button>月</button><button>季</button></div></div><div className="automation-stats"><div><b>1,248</b><small>自动动作</small></div><div><b>86.7%</b><small>策略内闭环</small></div><div><b>{blocked.length}</b><small>保护暂停</small></div><div><b>0</b><small>越权执行</small></div></div><HeatmapChart values={heatCells} theme={a.theme}/><div className="heatmap-labels"><span>6月</span><span>7月</span><span>8月</span><span>9月</span></div></section>
 </div>
 <div className="overview-kpis">{[[PhoneCall,'有效本人联络率','38.6%','+5.3%'],[Handshake,'方案确认率','27.4%','+2.8%'],[MagicWand,'自动闭环率','92.4%','+3.2%'],[CurrencyCircleDollar,'每回款案件成本','¥18.6','-6.1%']].map(([Icon,label,value,delta])=><section className="kpi-tile" key={label}><span className="kpi-icon"><Icon size={20}/></span><div><small>{label}</small><strong>{value}</strong></div><span className={delta.startsWith('-')?'positive-pill':'positive-pill'}>{delta}</span></section>)}</div>
 <section className="dashboard-card overview-table-card"><div className="overview-table-head"><div><span className="card-kicker">案件执行视图</span><strong>{a.visibleCases.length} 个在管案件</strong></div><div><select aria-label="筛选案件状态" value={status} onChange={e=>{setStatus(e.target.value);setSelected([])}}><option value="all">全部状态</option><option value="履约中">履约中</option><option value="blocked">保护暂停</option><option value="已结清">已结清</option></select><Scope value={a.scope} onChange={a.setScope}/><Search value={q} onChange={setQ} placeholder="搜索案件…"/></div></div>{selected.length>0&&<div className="bulk-bar"><b>已选 {selected.length} 个案件</b><button onClick={()=>a.notify('已将所选案件加入复核视图')}>加入复核</button><button onClick={()=>setSelected([])}>取消选择</button></div>}<div className="table-scroll"><table className="data-table overview-data-table"><thead><tr><th className="check-col"><input type="checkbox" aria-label="选择当前列表全部案件" checked={rows.length>0&&rows.every(r=>selected.includes(r.case_id))} onChange={selectAll}/></th><th>案件</th><th>AI 状态</th><th>下一步 / 暂停原因</th><th>确认净回款</th><th>应计佣金</th><th>更新</th><th>操作</th></tr></thead><tbody>{rows.map(c=><tr key={c.case_id} className={selected.includes(c.case_id)?'selected':''}><td className="check-col"><input type="checkbox" aria-label={`选择案件 ${c.case_id}`} checked={selected.includes(c.case_id)} onChange={()=>toggle(c.case_id)}/></td><td><button className="cell-title" onClick={()=>a.openCase(c.case_id)}>{c.case_id}</button><small>{c.package_id} · {['active','completed'].includes(c.governedPlan?.status)||c.plan?.status==='SIGNED'?'已签协议':'样本案件'}</small></td><td><Badge>{c.status}</Badge></td><td className="next-cell"><b>{c.blocked?'需要人工复核':'AI 自动执行'}</b><small>{c.blocked?c.reason:c.case_id==='C002'&&!a.paid?'补款差额 ¥1,016':'按授权持续核对'}</small></td><td className="number">{money(c.cash)}</td><td className="number">{money(c.commission)}</td><td className="muted">10:{String(42-c.case_id.slice(1)%20).padStart(2,'0')}</td><td><div className="row-actions"><IconButton icon={Eye} label={`查看案件 ${c.case_id}`} onClick={()=>a.openCase(c.case_id)}/><IconButton icon={DotsThree} label={`更多操作 ${c.case_id}`} onClick={()=>a.notify(`${c.case_id} 的更多操作仅作演示`)}/></div></td></tr>)}</tbody></table></div>{!rows.length&&<Empty/>}<div className="table-footer"><span>显示 {rows.length} / {a.visibleCases.length} · 仅当前工作空间</span><button className="text-link" onClick={()=>a.navigate('cases')}>查看全部案件 <ArrowRight size={14}/></button></div></section>
 </div>}
export function Assets(){const a=useApp();const [q,setQ]=useState('');return <><PageHead title="资产包" description="按委托、资料质量、可执行池和经营贡献管理长账龄资产。"><Button icon={UploadSimple} variant="primary" onClick={()=>a.setDialog({type:'import'})}>导入资产包</Button></PageHead><div className="table-toolbar"><Search value={q} onChange={setQ} placeholder="搜索资产包名称或编号…"/><span className="muted">{a.visiblePackages.length} 个资产包 · {a.visibleCases.length} 个案件</span></div><div className="asset-list">{a.visiblePackages.filter(p=>(p.title+p.package_id).toLowerCase().includes(q.toLowerCase())).map(p=>{const l=a.visibleLedger.filter(x=>x.package_id===p.package_id);const cases=a.visibleCases.filter(c=>c.package_id===p.package_id);const executable=cases.filter(c=>!c.blocked&&!['已结清','本期已足额'].includes(c.status)).length;const protectedCount=cases.filter(c=>c.blocked).length;const quality=Math.round(cases.reduce((s,c)=>s+c.dataQuality,0)/Math.max(1,cases.length));const cash=sum(l,'cash_yuan');const commission=sum(l,'commission_yuan');return <section className="asset-row" key={p.package_id}><div className="asset-heading"><span className="asset-icon"><FolderSimple size={27}/></span><div><h2>{p.title}</h2><p>{p.package_id} · {p.package_name}</p></div><Badge>委托中</Badge></div><Metrics items={[["在管案件",cases.length],["可执行池",executable],["保护暂停",protectedCount],["数据质量",`${quality}%`]]}/><div className="asset-economics"><span><small>确认净回款</small><b>{money(cash)}</b></span><span><small>应计佣金</small><b>{money(commission)}</b></span><span><small>佣金比例</small><b>{p.rate*100}%</b></span><span><small>模拟净贡献</small><b>{money(Math.max(0,commission-21.3))}</b></span></div><div className="asset-bottom"><span>委托期：{p.start_date} — {p.end_date} · 账龄以 3–5 年和 5 年以上为主</span><div><button className="text-link" onClick={()=>a.setDialog({type:'policy',package:p.package_id})}>查看授权策略</button><Button onClick={()=>{a.setScope(p.package_id);a.navigate('cases')}}>查看案件</Button><Button variant="primary" icon={Plus} onClick={()=>a.setDialog({type:'create',package:p.package_id})}>创建活动</Button></div></div></section>})}{!a.visiblePackages.some(p=>(p.title+p.package_id).toLowerCase().includes(q.toLowerCase()))&&<Empty/>}</div></>}
export function Cases(){const a=useApp();const [q,setQ]=useState('');const [tab,setTab]=useState('all');const [page,setPage]=useState(1);const signed=c=>['active','completed'].includes(c.governedPlan?.status)||c.plan?.status==='SIGNED';const rows=a.visibleCases.filter(c=>(a.scope==='all'||c.package_id===a.scope)&&(tab==='all'||(tab==='blocked'?c.blocked:tab==='quality'?c.dataQuality<70:signed(c)))&&(c.case_id+c.status+c.package_id+c.agingBucket).toLowerCase().includes(q.toLowerCase()));return <><PageHead title="案件" description="分开查看债务事实、业务状态、AI 执行状态与保护边界。"><Button onClick={()=>a.setCopilotOpen(true)}>用 AI 查询案件</Button><Button icon={DownloadSimple} onClick={()=>{downloadCSV('案件清单_演示.csv',['案件','资产包','账龄','质量','状态','确认净回款','应计佣金'],rows.map(c=>[c.case_id,c.package_id,c.ageMonths,c.dataQuality,c.status,c.cash,c.commission]));a.notify('案件清单已导出')}}>导出清单</Button></PageHead><Tabs value={tab} onChange={x=>{setTab(x);setPage(1)}} items={[{id:'all',label:'全部案件',count:a.visibleCases.length},{id:'signed',label:'已签协议'},{id:'blocked',label:'保护暂停'},{id:'quality',label:'低质量资料'}]}/><div className="table-toolbar"><Scope value={a.scope} onChange={s=>{a.setScope(s);setPage(1)}}/><Search value={q} onChange={s=>{setQ(s);setPage(1)}} placeholder="搜索案件、状态或账龄…"/><span className="muted small">点击案件查看事实、计划和工具证据</span></div><div className="table-scroll"><table className="data-table cases-table"><thead><tr><th>案件 / 账龄</th><th>资产包</th><th>转让余额</th><th>数据质量</th><th>业务状态</th><th>AI 状态 / 下一步</th><th>确认净回款</th><th/></tr></thead><tbody>{rows.slice((page-1)*8,page*8).map(c=><tr key={c.case_id}><td><button className="cell-title" onClick={()=>a.openCase(c.case_id)}>{c.case_id}</button><small>{c.agingBucket} · {c.ageMonths} 个月</small></td><td>{c.package_id}<small>{signed(c)?'协议已签署':'尚无生效协议'}</small></td><td className="number">{money(c.transfer_balance_yuan)}</td><td><span className={`quality-score ${c.dataQuality<70?'low':''}`}>{c.dataQuality}%</span><small>{c.contactability}</small></td><td><Badge>{c.status}</Badge></td><td><b className="next-text">{c.blocked?'保护暂停':'可评估执行'}</b><small>{c.blocked?c.reason:c.nextAllowed}</small></td><td className="number">{money(c.cash)}<small>佣金 {money(c.commission)}</small></td><td><IconButton icon={ArrowUpRight} label={`查看案件 ${c.case_id}`} onClick={()=>a.openCase(c.case_id)}/></td></tr>)}</tbody></table></div>{!rows.length&&<Empty/>}<div className="table-footer"><span>共 {rows.length} 个案件 · 仅当前工作空间</span><div><IconButton icon={CaretLeft} label="上一页" disabled={page===1} onClick={()=>setPage(page-1)}/><span className="page-number">{page}</span><IconButton icon={CaretRight} label="下一页" disabled={page*8>=rows.length} onClick={()=>setPage(page+1)}/></div></div></>}
export function Payments(){
 const a=useApp();
 const [tab,setTab]=useState('回款流水');
 const [q,setQ]=useState('');
 const [period,setPeriod]=useState('all');
 const base=a.visibleLedger.filter(x=>(a.scope==='all'||x.package_id===a.scope)&&(period==='all'||x.booked_date.startsWith('2026-09')));
 const rows=base.filter(x=>(x.transaction_id+x.case_id).toLowerCase().includes(q.toLowerCase())).slice().sort((x,y)=>y.booked_date.localeCompare(x.booked_date)||y.transaction_id.localeCompare(x.transaction_id));
 const summary=a.financialOverview.summary;
 const useServerSummary=a.scope==='all'&&period==='all'&&summary;
 const cash=useServerSummary?summary.confirmed_net_recovery_cents/100:sum(base,'cash_yuan');
 const eligible=useServerSummary?summary.commission_eligible_recovery_cents/100:sum(base,'eligible_cash_yuan');
 const accrued=useServerSummary?summary.accrued_commission_cents/100:sum(base,'commission_yuan');
 const settled=useServerSummary?summary.settled_commission_cents/100:0;
 const collected=useServerSummary?summary.collected_commission_cents/100:0;
 const pendingCount=summary?.pending_receipt_count??a.financialOverview.pendingReceipts.length;
 const commissionRows=a.financialOverview.commissionLedger.filter(row=>['settlement','collection'].includes(row.event_type)&&(period==='all'||row.occurred_at.startsWith('2026-09')));
 const callbackReady=a.backendStatus!=='connected'||(a.financialOverview.webhookReady&&a.financialOverview.sandboxEnabled);
 const exportRows=()=>{downloadCSV('回款与佣金_演示.csv',['交易号','案件','到账日期','净回款','计佣回款','应计佣金','计佣依据'],rows.map(x=>[x.transaction_id,x.case_id,x.booked_date,x.cash_yuan,x.eligible_cash_yuan,x.commission_yuan,reasonText[x.reason]]));a.notify('当前筛选的回款与佣金证据已导出')};
 return <><PageHead title="回款与佣金" description="验签回执进入不可变账簿后，才更新履约、计佣、结算与实收。"><Button onClick={()=>a.setCopilotOpen(true)}>用 AI 查询指标</Button><Button icon={DownloadSimple} onClick={exportRows}>导出明细</Button>{a.tenant==='TENANT_A'&&<Button variant="primary" disabled={a.paid||a.receivingPayment||!callbackReady} onClick={()=>a.setDialog({type:'receipt'})}>{a.paid?'模拟回调已处理':a.receivingPayment?'正在入账…':callbackReady?'模拟支付回调':'支付沙箱未就绪'}</Button>}</PageHead>
 <section className="pending-payment"><WarningCircle size={19}/><span><b>{pendingCount} 笔回执等待复核</b><small>{a.backendStatus==='connected'?(a.financialOverview.webhookReady?`${a.financialOverview.webhookProvider} · HMAC v1 · 服务端账簿`:'签名密钥尚未配置或不可解析'):a.hostedDemo?'在线交互沙箱：不会写入服务端账簿':'离线演示：不会写入服务端账簿'}；提案人与复核人分离，批准前不进入钱指标。</small></span><button className="text-link" onClick={()=>setTab('回执复核')}>查看复核队列 <ArrowRight size={14}/></button></section>
 <div className="table-toolbar"><Scope value={a.scope} onChange={a.setScope}/><select aria-label="回款日期范围" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">累计至今</option><option value="month">2026 年 9 月</option></select></div>
 <Metrics className="five-metrics" items={[["确认净回款",money(cash)],["计佣回款",money(eligible)],["应计佣金",money(accrued)],["确认结算",money(settled)],["实际收佣",money(collected)]]}/>
 <Tabs value={tab} onChange={setTab} items={['回款流水','佣金明细','结算记录',{id:'回执复核',label:'回执复核',count:pendingCount}]}/>
 {tab==='回执复核'?<ReceiptReviewQueue/>:tab==='结算记录'?<>{commissionRows.length?<div className="table-scroll"><table className="data-table payment-table"><thead><tr><th>佣金事件</th><th>业务引用</th><th>金额</th><th>发生时间</th><th>登记人</th></tr></thead><tbody>{commissionRows.map(row=><tr key={row.event_id}><td><Badge status="completed">{row.event_type==='settlement'?'确认结算':'实际收佣'}</Badge><small>{row.event_id}</small></td><td>{row.reference}</td><td className="number">{money(row.amount_cents/100)}</td><td>{row.occurred_at.slice(0,16).replace('T',' ')}</td><td>{row.created_by}</td></tr>)}</tbody></table></div>:<Empty title="尚无佣金结算记录" description="应计佣金不会自动视为已结算或实际收佣。"/>}</>:<><div className="table-toolbar"><Search value={q} onChange={setQ} placeholder="搜索交易号或案件编号…"/><span className="muted small">点击交易查看验签摘要、幂等、匹配、账簿事件和计佣依据</span></div><div className="table-scroll"><table className="data-table payment-table"><thead><tr><th>{tab==='回款流水'?'交易 / 来源':'计佣依据 / 规则'}</th><th>案件 / 分配</th><th>净回款</th><th>核验状态</th><th>{tab==='回款流水'?'计佣回款':'比例'}</th><th>应计佣金</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.transaction_id}><td><button className="cell-title" onClick={()=>a.setDialog({type:'payment',transaction:x})}>{tab==='回款流水'?x.transaction_id:reasonText[x.reason]}</button><small>{x.booked_date} · {x.source||'AMC 脱敏回款文件'}</small></td><td><button className="text-link" onClick={()=>a.openCase(x.case_id,'回款')}>{x.case_id}</button><small>{x.allocation||'按支付日期与方案分配'}</small></td><td className={x.cash_yuan<0?'number negative':'number'}>{money(x.cash_yuan)}</td><td><Badge status={x.cash_yuan<0?'neutral':'completed'}>{x.cash_yuan<0?'已冲回':'验签并确认'}</Badge><small>{a.backendStatus==='connected'?'幂等 · 账簿已写入':'演示事件 · 未写服务端'}</small></td><td>{tab==='回款流水'?money(x.eligible_cash_yuan):(x.eligible?`${x.rate*100}%`:'不计佣')}</td><td className="number">{money(x.commission_yuan)}</td><td><button className="text-link" onClick={()=>a.setDialog({type:'payment',transaction:x})}>证据 <ArrowUpRight size={13}/></button></td></tr>)}</tbody></table></div>{!rows.length&&<Empty/>}<div className="table-footer"><span>共 {rows.length} 笔 · 人民币元 · 当前工作空间</span><span>{a.backendStatus==='connected'?'服务端账簿':a.hostedDemo?'在线交互沙箱':'离线演示数据'}</span></div></>}
 </>}

function ReceiptReviewQueue(){const a=useApp();const pending=a.financialOverview.pendingReceipts;const reviews=a.financialOverview.reconciliations;const reviewFor=id=>reviews.find(row=>row.receipt_id===id);const closed=reviews.filter(row=>row.status!=='pending_review');return <div className="reconciliation-queue"><div className="reconciliation-principle"><ShieldCheck size={20}/><span><b>Maker–Checker 双人复核</b><small>系统只生成租户内候选建议；提案人不能复核自己的提案，批准时重新校验案件财务档案并原子入账。</small></span></div>{pending.length?<div className="table-scroll"><table className="data-table reconciliation-table"><thead><tr><th>回执 / 来源</th><th>金额</th><th>异常原因</th><th>当前阶段</th><th>建议案件</th><th>责任人</th><th/></tr></thead><tbody>{pending.map(receipt=>{const review=reviewFor(receipt.id);return <tr key={receipt.id}><td><b>{receipt.provider_event_id}</b><small>{receipt.provider} · HMAC {receipt.signature_version}</small></td><td className="number">{money(receipt.amount_cents/100)}<small>{receipt.currency}</small></td><td>{receipt.failure_code==='human_review_pending'?'人工复核中':receipt.failure_code||'待人工确认'}<small>未进入钱指标</small></td><td><Badge status={review?'paused':'neutral'}>{review?'等待独立复核':'待创建提案'}</Badge></td><td>{review?.proposed_case_id||receipt.case_id||'—'}<small>{review?`证据 ${review.evidence_digest.slice(0,8)}…`:'需核对案件归属'}</small></td><td>{review?.proposed_by||'待领取'}<small>{review?'提案人':'运营人员'}</small></td><td><Button variant={review?'primary':'secondary'} onClick={()=>a.setDialog({type:'reconciliation',receipt})}>{review?'进入复核':'创建提案'}</Button></td></tr>})}</tbody></table></div>:<Empty title="没有待复核回执" description="所有已验签回执均已匹配、驳回或保持隔离。" action={a.backendStatus==='connected'&&a.financialOverview.sandboxEnabled?<Button onClick={()=>a.createReconciliationSample().catch(error=>a.notify(`样本创建失败：${error.message}`))}>生成待复核沙箱回执</Button>:null}/>} {closed.length>0&&<><h3 className="section-label separated">最近复核记录</h3><div className="review-history">{closed.slice(0,5).map(row=><div key={row.id}><Badge status={row.status==='approved'?'completed':'neutral'}>{row.status==='approved'?'已批准':'已驳回'}</Badge><span><b>{row.proposed_case_id}</b><small>{row.proposed_by} → {row.reviewed_by||'—'} · v{row.version}</small></span><code>{row.evidence_digest.slice(0,12)}…</code></div>)}</div></>}</div>}
