import React,{useState} from 'react';
import {useApp} from './context';
import {platformApi} from './api';
import {useRemoteResource} from './remote-resource';
import {Badge,Button,Field,Modal} from './ui';
const labels={trial:'试用',active:'已激活',grace:'宽限期',suspended:'已暂停',closed:'已关闭'};
const targets={trial:['active','suspended','closed'],active:['grace','suspended','closed'],grace:['active','suspended','closed'],suspended:['active','closed'],closed:[]};

export function TenantGovernance(){
 const a=useApp(),connected=a.backendStatus==='connected',admin=connected&&a.identity.role==='admin';
 const resource=useRemoteResource(connected,`${a.tenant}:${a.identity.role}`,async()=>{const [lifecycle,proposals]=await Promise.all([platformApi.lifecycle(a.tenant),admin?platformApi.lifecycleProposals(a.tenant):Promise.resolve([])]);return {lifecycle,proposals}});
 const current=resource.data?.lifecycle,proposals=resource.data?.proposals||[],pending=proposals.some(p=>p.status==='pending_review');
 const [form,setForm]=useState(null),[review,setReview]=useState(null),[note,setNote]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const mutate=async action=>{if(busy)return;setBusy(true);setError('');try{await action();setForm(null);setReview(null);setAck(false);resource.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <section aria-label="租户生命周期治理">
  <section className="tenant-lifecycle-card"><div><span className="eyebrow">TENANT LIFECYCLE · {current?`v${current.version}`:'待接入'}</span><h2>{a.organization[a.tenant]}</h2><p>{current?`${current.region} · 数据保留 ${current.data_retention_days} 天 · ${current.contract_reference||'待登记合同引用'}`:connected?'尚未取得生命周期证据':'演示工作空间，未连接企业生命周期服务'}</p></div><Badge status={current?.stage==='active'?'completed':'paused'}>{current?labels[current.stage]:connected?'待读取':'演示'}</Badge></section>
  <p className="notice">激活、暂停、关闭和恢复会影响租户权益；管理员提交提案，由另一名管理员独立复核。关闭后不能通过本流程重新激活。</p>
  {(resource.error||error)&&<p className="form-error" role="alert">{resource.error||error}</p>}
  <div className="material-toolbar"><Button disabled={!admin||!current||pending||!targets[current?.stage]?.length||busy} onClick={()=>{setAck(false);setError('');setForm({target_stage:targets[current.stage][0],expected_lifecycle_version:current.version,region:current.region,data_retention_days:current.data_retention_days,trial_ends_at:current.trial_ends_at,contract_reference:current.contract_reference||'',customer_success_owner:current.customer_success_owner||'',proposal_reason:''})}}>提交生命周期变更</Button><Button disabled={!connected||resource.busy||busy} onClick={resource.refresh}>刷新生命周期</Button>{!connected&&<Button onClick={()=>a.navigate('pilot')}>查看企业接入条件</Button>}</div>
  {admin&&proposals.map(row=><article key={row.id} className="service-row"><div><b>{labels[row.current_stage]} → {labels[row.target_stage]}</b><p>{row.proposal_reason}</p><small>{row.id} · 提案人 {row.proposed_by} · {row.status}</small></div>{row.status==='pending_review'&&<Button disabled={busy||row.proposed_by===a.identity.actor_id||!!resource.error} onClick={()=>{setReview(row);setNote('');setAck(false);setError('')}}>独立复核生命周期</Button>}{row.status==='pending_review'&&row.proposed_by===a.identity.actor_id&&<small>等待另一名管理员</small>}</article>)}
  {form&&<Modal title="租户生命周期变更提案" onClose={()=>setForm(null)} footer={<><Button onClick={()=>setForm(null)}>取消</Button><Button variant="primary" disabled={busy||!ack||form.proposal_reason.trim().length<8||(form.target_stage==='active'&&!form.contract_reference.trim())} onClick={()=>mutate(()=>platformApi.proposeLifecycle(a.tenant,form))}>提交独立复核</Button></>}><Field label="目标生命周期"><select value={form.target_stage} onChange={e=>setForm({...form,target_stage:e.target.value})}>{targets[current.stage].map(stage=><option key={stage} value={stage}>{labels[stage]}</option>)}</select></Field><Field label="合同或试点批准引用"><input maxLength={160} value={form.contract_reference} onChange={e=>setForm({...form,contract_reference:e.target.value})}/></Field><Field label="数据保留天数"><input type="number" min="30" max="3650" value={form.data_retention_days} onChange={e=>setForm({...form,data_retention_days:Number(e.target.value)})}/></Field><Field label="生命周期变更依据"><textarea maxLength={1000} value={form.proposal_reason} onChange={e=>setForm({...form,proposal_reason:e.target.value})}/></Field><label className="check-agreement"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>已核验访问与数据保留影响，提案须独立管理员复核。</span></label>{error&&<p role="alert">{error}</p>}</Modal>}
  {review&&<Modal title="独立复核生命周期" onClose={()=>setReview(null)} footer={<><Button disabled={busy||!ack||note.trim().length<4} onClick={()=>mutate(()=>platformApi.decideLifecycle(a.tenant,review.id,'reject',review.version,note))}>驳回生命周期变更</Button><Button variant="primary" disabled={busy||!ack||note.trim().length<4} onClick={()=>mutate(()=>platformApi.decideLifecycle(a.tenant,review.id,'approve',review.version,note))}>批准生命周期变更</Button></>}><p>{labels[review.current_stage]} → {labels[review.target_stage]} · {review.contract_reference||'无合同引用'}</p><Field label="生命周期复核意见"><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></Field><label className="check-agreement"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>已独立核验合同、保留策略和访问影响。</span></label>{error&&<p role="alert">{error}</p>}</Modal>}
 </section>;
}
