import React,{useEffect,useRef} from 'react';
import {X,ArrowRight,CheckCircle,Clock,PauseCircle,WarningCircle,MagnifyingGlass,Robot,ArrowUpRight} from '@phosphor-icons/react';
import {money} from './model';
import {useApp} from './context';
export function Button({children,icon:Icon,variant='secondary',className='',...props}){return <button className={`btn ${variant} ${className}`} {...props}>{Icon&&<Icon size={17}/>}<span>{children}</span></button>}
export function IconButton({icon:Icon,label,...props}){return <button className="icon-btn" title={label} aria-label={label} {...props}><Icon size={19}/></button>}
export function Badge({status,children}){const text={running:'运行中',completed:'已完成',paused:'已暂停',blocked:'保护暂停'};const type=status||(/暂停|待核|耗尽|到期|缺失|待补|失败|停止/.test(children)?'blocked':/已|履约中/.test(children)?'running':'neutral');const Icon={running:Clock,completed:CheckCircle,paused:PauseCircle,blocked:WarningCircle}[type];return <span className={`badge ${type}`}>{Icon&&<Icon size={12} weight={type==='completed'?'fill':'regular'}/>} {children||text[status]||status}</span>}
export function PageHead({eyebrow,title,description,children}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="head-actions">{children}</div></div>}
export function Tabs({items,value,onChange}){return <div className="tabs" role="tablist">{items.map(item=>{const o=typeof item==='string'?{id:item,label:item}:item;return <button role="tab" aria-selected={value===o.id} className={value===o.id?'active':''} onClick={()=>onChange(o.id)} key={o.id}>{o.label}{o.count!==undefined&&<span className="count">{o.count}</span>}</button>})}</div>}
export function Search({value,onChange,placeholder='搜索…'}){return <div className="search-input"><MagnifyingGlass size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<IconButton icon={X} label="清空搜索" onClick={()=>onChange('')}/>}</div>}
export function Metrics({items,className=''}){return <div className={`metrics ${className}`}>{items.map(([label,value,note])=><div className="metric" key={label}><div>{label}</div><strong>{value}</strong>{note&&<small>{note}</small>}</div>)}</div>}
export function Empty({title='暂无匹配结果',description='试试调整筛选条件，或清空搜索。',action}){return <div className="empty"><MagnifyingGlass size={30}/><h3>{title}</h3><p>{description}</p>{action}</div>}
export function Modal({title,subtitle,children,onClose,wide=false,footer}){const ref=useRef(null);useEffect(()=>{const before=document.activeElement;const el=ref.current;const focusable=()=>[...el.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled);(el.querySelector('input:not([type=checkbox]):not([readonly]),textarea,select')||focusable()[0])?.focus();function keys(e){if([...document.querySelectorAll('.overlay')].at(-1)!==el.parentElement)return;if(e.key==='Escape')onClose();if(e.key==='Tab'){const f=focusable();if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0]?.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);before?.focus()};},[]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title} ref={ref}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><IconButton icon={X} label="关闭弹窗" onClick={onClose}/></header><div className="modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</section></div>}
export function Field({label,children,hint,error}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}{error&&<small className="error">{error}</small>}</label>}
export function KeyValue({items}){return <dl className="kv">{items.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
export function EventFeed({compact=false}){const a=useApp();const events=a.events.filter(e=>e.tenant===a.tenant&&(a.page!=='activities'||a.scope==='all'||a.visibleCases.find(c=>c.case_id===e.caseId)?.package_id===a.scope));return <section className={`event-feed ${compact?'compact':''}`}><div className="section-title"><h2><Robot size={21}/> AI 执行动态</h2><span className="live-dot"/></div><p className="muted small">模拟运行 · 每一步都有依据</p><div className="timeline">{events.slice(0,compact?3:5).map(e=><div className="timeline-item" key={e.id}><span className="event-time">{e.time}</span><CheckCircle className="timeline-icon" size={17}/><div><button className="text-strong" onClick={()=>a.openCase(e.caseId)}>{e.caseId} {e.title}</button><p>{e.detail}</p><button className="text-link small" onClick={()=>a.openCase(e.caseId,'记录')}>查看依据 <ArrowUpRight size={13}/></button></div></div>)}</div><button className="text-link" onClick={()=>a.navigate('logs')}>查看全部运行记录 <ArrowRight size={16}/></button></section>}
export function Money({value}){return <span className="number">{money(value)}</span>}
